### ISSUE TITLE
If WebSocket closed, stale data is presented without warning

### ISSUE THREAD

**Issue by carlpett** [jippi/hashi-ui#119]
My machine is in sleep mode during the night, and when I opened it up in the morning all the data shown in nomad-ui was the "last shown". No matter what job or allocation I clicked, I got the details for the same thing I last viewed yesterday. After some confusion, I checked the console output and there was a lot of "Websocket is in closing or closed state" errors. A hard refresh fixed it.

Proposed fixes:
1. Show some sort of error instead of whatever was loaded last time in that view (job/allocation/etc) if there is no connection to the backend
2. Attempt to reconnect if connection is lost

**Comment by iverberk** [comment]
I'm sorry you had a bad experience. We will do both those things: visually indicate when the frontend has a valid connection to the backend and retry logic in case of failures. This has been on the list for a while and will be implemented asap. Thanks for reporting!

**Comment by jippi** [comment]
This is my next attack item :)

**Comment by jippi** [comment]
This has been fixed in https://github.com/jippi/hashi-ui/releases/tag/v0.5.5 :)
