### ISSUE TITLE
Auto refresh minimizes extended raw arrays

### ISSUE THREAD

**Issue by kaskavalci** [jippi/hashi-ui#127]
Raw data is not all expanded and it is very hard to investigate with auto refresh on. Extended arrays are reseted in every ~5 seconds. Example:

![](http://i.giphy.com/3oz8xBQnH6SMHI6McE.gif)

**Comment by jippi** [comment]
yeah, it's pain in the ass :( 

Maybe the JSON should be loaded once and never refreshed

**Comment by kaskavalci** [comment]
Good idea or maybe have a refresh button for json files. It would really ease my life :)

**Comment by jippi** [comment]
@kaskavalci i think this should be fixed now, please let me know if you see this issue still :)
