### ISSUE TITLE
Support querying other regions

### ISSUE THREAD

**Issue by bastiaanb** [jippi/hashi-ui#130]
Nomad-ui shows information only for the local region. It would be nice to be able to select other regions as well, like Consul can.

**Comment by jippi** [comment]
@bastiaanb i agree! i personally only use one region at the moment, so my urgency to add this in is currently not super high - is it something you could help out with? :)

**Comment by jippi** [comment]
@bastiaanb can you try and test #170 ? :)

**Comment by bastiaanb** [comment]
Ha, thanks for the update. Sorry for not responding earlier! I'll try it out tomorrow, time to revive my Devoxx talk multi region setup.

**Comment by jippi** [comment]
Fixed in https://github.com/jippi/hashi-ui/releases/tag/v0.12.0
