### ISSUE TITLE
Error: nomad-ui/backend not a go package or not in GOPATH.

### ISSUE THREAD

**Issue by jemc** [jippi/hashi-ui#142]
As recently as version 0.1.3, I was able to build from source using `env GOBUILD=linux-amd64 make`.

Now, using latest master at the time of this writing (341bfebbd4ff18b6312ae79be5c0eecb79cadec9), it seems to require me to set `GOPATH`:

```
--> Running go fmt
--> Running go tool vet -all ./backend/connection.go ./backend/main.go ./backend/hub.go ./backend/nomad.go ./backend/actions.go
Installing github.com/kardianos/govendor
package github.com/kardianos/govendor: cannot download, $GOPATH not set. For more details see: go help gopath
Installing github.com/jteeuwen/go-bindata/...
package github.com/jteeuwen/go-bindata/...: cannot download, $GOPATH not set. For more details see: go help gopath
Installing github.com/elazarl/go-bindata-assetfs/...
package github.com/elazarl/go-bindata-assetfs/...: cannot download, $GOPATH not set. For more details see: go help gopath
Makefile:10: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 1
```

When I do set `GOPATH` to point where I usually point it to on the occasions that I need to build someone's Go project, I receive an error that `nomad-ui/backend` is "not a go package or not in GOPATH":

```
$ env GOPATH="$HOME/.go" GOBUILD=linux-amd64 make build
--> Running go fmt
--> Running go tool vet -all ./backend/bindata_assetfs.go ./backend/connection.go ./backend/main.go ./backend/hub.go ./backend/nomad.go ./backend/actions.go
Installing github.com/kardianos/govendor
Installing github.com/jteeuwen/go-bindata/...
Installing github.com/elazarl/go-bindata-assetfs/...
=> building frontend ...
make -C frontend build
make[1]: Entering directory '/home/jemc/1/code/gitx/nomad-ui/frontend'
=> building frontend ...
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm run-script build

> nomad-ui@0.0.1 build /home/jemc/1/code/gitx/nomad-ui/frontend
> webpack --config webpack-prod.config.js -p --progress

Hash: d2d278c821907b52376f  
Version: webpack 1.13.3
Time: 63327ms
                                               Asset       Size  Chunks             Chunk Names
         static/c45f7de008ab976a8e817e3c0e5095ca.svg     164 kB          [emitted]  
         static/f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]  
       static/448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]  
         static/e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]  
         static/89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]  
         static/71394c0c7ad6c1e7d5c77e8ac292fba5.eot    58.7 kB          [emitted]  
        static/b38ef310874bdd008ac14ef3db939032.woff    58.6 kB          [emitted]  
         static/01798bc13e33afc36a52f2826638d386.ttf    58.5 kB          [emitted]  
        static/fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]  
         static/b04822fc8655021cde2c2f865dce153d.jpg     438 kB          [emitted]  
                 static/main.6e0e3abd437ec97028fe.js     916 kB       0  [emitted]  main
    static/main.a6416efbc5794a3dd7c0c9270d7b3e60.css     190 kB       0  [emitted]  main
             static/main.6e0e3abd437ec97028fe.js.map    6.81 MB       0  [emitted]  main
static/main.a6416efbc5794a3dd7c0c9270d7b3e60.css.map  125 bytes       0  [emitted]  main
                                         favicon.png  949 bytes          [emitted]  
                                          index.html       1 kB          [emitted]  
   [0] multi main 40 bytes {0} [built]
    + 1128 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 7 hidden modules
Child extract-text-webpack-plugin:
        + 7 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
make[1]: Leaving directory '/home/jemc/1/code/gitx/nomad-ui/frontend'
make -C backend build
make[1]: Entering directory '/home/jemc/1/code/gitx/nomad-ui/backend'
=> installing go-ps library...
go get github.com/mitchellh/go-ps
=> building /home/jemc/1/code/gitx/nomad-ui/backend/build/nomad-ui-linux-amd64 ...
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 govendor build -o /home/jemc/1/code/gitx/nomad-ui/backend/build/nomad-ui-linux-amd64
Error: Package "/home/jemc/1/code/gitx/nomad-ui/backend" not a go package or not in GOPATH.
Makefile:13: recipe for target '/home/jemc/1/code/gitx/nomad-ui/backend/build/nomad-ui-linux-amd64' failed
make[1]: *** [/home/jemc/1/code/gitx/nomad-ui/backend/build/nomad-ui-linux-amd64] Error 2
make[1]: Leaving directory '/home/jemc/1/code/gitx/nomad-ui/backend'
Makefile:43: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by Nomon** [comment]
looks like nomad-ui is not cloned under the correct GOPATH, you have your clone path of nomad-ui outside of the GOPATH and when nomad-ui imports a sub package from $GOPATHsrc/github.com/iverberk/nomad-ui/backend it cannot find the package. Either use go get or clone it under GOPATH where it should be at (ie. $GOPATH/src/github.com... instead of /home/jemc/1/code/gitx/nomad-ui/).

**Comment by jemc** [comment]
Out of curiosity, how does this work in Travis CI?  As far as I know Travis CI doesn't clone the repo into a magical Go-sanctioned path under `src/github.com`, yet, it's still able to build the code.  How is it done in this case?

**Comment by Nomon** [comment]
https://docs.travis-ci.com/user/languages/go#Go-Import-Path

**Comment by jemc** [comment]
As far as I can tell, using `go get` doesn't allow you to specify a git tag to fetch, and always fetches master, so that option is out.

I find it pretty darn obnoxious that a piece of Go source code written using these conventions/tooling can only be built in a specific, deeply nested path in a specific location.  Especially when this very same project did not formerly have that restriction.

I've tried various workarounds with symbolic links, but I think I'm missing the necessary context for coming up with a workaround for this silly restriction.

I'm going to ask someone on my team who actually _likes_ dealing with Go to pick this up from here and see if they can come up with a solution for in-source builds.

**Comment by jippi** [comment]
this is my env 

```
GOPATH=$HOME/src/go-lang
~/src/go-lang/src/github.com/iverberk/nomad-ui # <- source
make bootstrap
make build
NOMAD_ADDR=http://localhost:4646 ./backend/build/nomad-ui-darwin-amd64

cd ~/src/go-lang/src/github.com/iverberk/nomad-ui ; npm start
```

**Comment by jemc** [comment]
The team member I talked to, who uses Go frequently said "the environment that this project is requiring is something I've never experienced before".

Given that this project (as recently as `0.1.3`) did not always require to be cloned into a magic directory, and given that many Go projects also do not have this requirement, would it be possible to make a patch that allows the package to refer to itself without passing through `GOPATH`?  I don't have the necessary Go expertise to make such a patch, but it would be greatly appreciated.

Also, as a small unrelated side issue, the `README.md` still says you can build with `make` alone (using the implicit default target), but the `Makefile` now requires you to specify the `build` target - that is, it requires you to run `make build` instead of just `make`.  So it seems the `README.md` should be updated to reflect the build system changes, or they should be patched further.

**Comment by jippi** [comment]
I'm far from an go expert, but nomad itself require, afaik, the same rigid structure to work - so don't think its too alien or steep requirement to have. 

The readme should be updated with the additional steps - did my steps in previous reply to this ticket make the environment work for you?

**Comment by jemc** [comment]
I haven't tried cloning into the magic directory, but I don't doubt that it works.  I was still hoping there would be some discussion of a patch to avoid this requirement.  Either that, or a workaround involving symlinks but so far none of the workarounds I've tried have worked, so I've given up on trying to build the project.

**Comment by jippi** [comment]
@jemc I've tried to describe the expectations and workflow i use myself here: https://github.com/jippi/hashi-ui/blob/master/DEVELOPMENT.md

Please let me know if it helps - and if there is any steps that I can take to improve the flow for you

**Comment by alliyaan** [comment]
sudo mkdir -p $GOPATH/src/github.com/skydive-project
sudo git clone https://github.com/skydive-project/skydive.git $GOPATH/src/github.com/skydive-project/skydive
cd $GOPATH/src/github.com/skydive-project/skydive
sudo make install


**ali@ali-machine /src/github.com/skydive-project/skydive $** sudo make install
go get github.com/kardianos/govendor
/bin/govendor sync
make: /bin/govendor: Command not found
Makefile:104: recipe for target 'govendor' failed
make: *** [govendor] Error 127
help ..!
