### ISSUE TITLE
npm start can't start the webpack-dev-server

### ISSUE THREAD

**Issue by peeekkk** [jippi/hashi-ui#149]
I cloned repository and checked out tag v0.3.1. (same issue with master branch)
When I run `npm install; npm start`, it prints out error messages as shown below.
![npm start err](https://cloud.githubusercontent.com/assets/20275238/20614281/7e4b5e94-b307-11e6-85e3-356b8747aa73.png)

And if I visit the url localhost:3333/index.html, I got a blank page with only bundle.js loaded:
```html
<body>
    <div id="app"></div>
    <script src="/static/bundle.js"></script>
</body>
```
And bundle.js is approx. 8.7MB.

I tried this with a new virtual machine with freshly installed Golang and Node.js, and still got the same error.

**Comment by jippi** [comment]
Hi @peeekkk !

So sorry I missed this issue previously.. Can you give https://github.com/jippi/hashi-ui/blob/master/DEVELOPMENT.md a look and let me know if it fixes your problems?
