### ISSUE TITLE
Show port mappings in the allocation info

### ISSUE THREAD

**Issue by far-blue** [jippi/hashi-ui#152]
Where an allocation has port mappings it would be good to show these - possibly with an easy-to-copy format of `<ip>:<port>` somewhere. It would be good to see the port label, nomad assigned port number, whether the port is static and, for docker containers, the map information for that port into the container.

**Comment by jippi** [comment]
i agree! :)

**Comment by lfarnell** [comment]
@jippi let me take a stab at this. I think I know how I would do it

**Comment by jippi** [comment]
@lfarnell that would be amazing!

**Comment by hsmade** [comment]
@jippi I think we covered this, right?

**Comment by jippi** [comment]
yep!
