### ISSUE TITLE
Re-visting UI base path improvements

### ISSUE THREAD

**Issue by vancluever** [jippi/hashi-ui#156]
Hey all,

I was wondering if we could re-visit #15. This ticket was opened to see if there was a way to get the UI to work on a different prefix other than `/`. The main use case, of course, being full support of reverse proxies.

My use case, in particular, is I'm trying to build a protected front-end proxy to route different paths to both the Consul and Nomad UIs, ie:

`/consul` to Consul (ie: `http://localhost:8500/`)
`/nomad` to Nomad via hashi-ui (ie: `http://localhost:3000/`)

The problem with both of these *was*, but now fixed for Consul as far as I can see (see Consul PR below) is that neither of the tools are specifically geared for proxies:

 * Consul did not pass a full URL path that included the host in the `Location:` header. I fixed this in hashicorp/consul#2585. So far as I can see hashi-ui does not have this issue.
 * Both tools were also not handling path properly in their content, opting to load content from a hard `/` without taking into account the location that is accessing it. Again I fixed this in Consul, but hashi-ui is stumping me.

I managed to get it so far as to ensure that there were no 404s anymore - so via gathering details of the called URL from things like `window.location`, I was able get all the webpack content loaded in `index.html.ejs` and the websocket URL proxied and loaded in `src/sagas/event.js`, but now I'm still getting a WSOD with no indication as to what is wrong (no JS console errors, and no errors or 404s generated by the respective servers).

At this point I'm stumped and was hoping that someone could help. I can do the work no sweat, but JS isn't a first language of mine, let alone React or where ever else routes or links would still need to be modified. Maybe just a hint as to where to go from here would be nice.

As to why I'm pushing this after the issue has been dropped - I would *really* like to have a central portal for both Nomad and Consul (and possibly any other standalone UIs for the Hashistack that come out of the woodwork at a later time). This allows me to protect these features (ie: with things like OpenID Connect, LDAP, SAML, etc) in addition to having a consistent entry point for these resources. It kind of breaks workflow, not to mention complicates configs, when I have to say that Consul is at `example.com/consul`, yet Nomad is at `example.com:3000`, for example. Proxy only gets you part of the way there, things like `ProxyPass/ProxyPassReverse` for Apache and `proxy_pass` (for nginx) only proxy headers and requests, not content. Using things like `mod_substitute` or `sub_filter`, especially in the absence of references like `http://example.com:3000` are quite fragile and IMO not an acceptable way of supporting reverse proxies in content.

It just seems like I'm nearly all the way there, hoping the core team like @jippi and @iverberk would like to re-visit this.

**Comment by jippi** [comment]
@vancluever this is not a personal priority at this time, but i can give it a shot later this week to gauge how easy it would be to hack.

Can you provide me a docker image or some stock configurations that you would like to work out of the box? Then i can try to make things work from there :) 

I personally run each service on a different port (`8500` for consul  `3000` for nomad) and just redirect `infra.something/nomad` to the right host+port :) 

feel free to drop by the gitter room if you want to discuss

**Comment by vancluever** [comment]
Thanks @jippi, yeah that was something I was hoping to avoid (redirecting to native ports), while not necessarily a big deal having the single endpoint just seems cleaner and possibly mentally easier to gateway.

I have all the configs and what not dockerized but I never got around to uploading them this weekend before I had to go this morning - I'll push later and let you know on gitter. :)

**Comment by jippi** [comment]
Thanks! :)

**Comment by vancluever** [comment]
Hey @jippi these are up now. Check out 6e80714993d0fc5b65ad56963c37a623cbd27d26 to get an idea of what I've done so far (not saying this code is 100% optimal ;) )

Also my Docker container can be found here: https://github.com/vancluever/hashistack-admin-fe

Let me know your thoughts!

**Comment by vancluever** [comment]
OK, I think I made progress by figuring out how to use `useBasename` in React.

So now the main issue I'm coming across is that, of course, `window.location.pathname` is unstable across reloads as once a route is loaded and the location has changed in the browser, the next reload brings a new relative path and attempts to load the main CSS and JS off of that path. Not to mention that using that as a basename will probably also mess up the routes once reloaded.

Trying to think of a way that we could do this... will add the commit in the meantime.

**Comment by vancluever** [comment]
Hey @jippi my branch is now loading the UI behind a reverse proxy properly. Runtime config is supplied via a `config.js` (as mentioned in Gitter) that gets loaded in regardless of the route (basically any URI ending in `/config.js` gets the content). This is the cleanest way I could think to do it so far. I still need to update the docs but you can see what's needed in the commits.

Let me know what you think - will add docs and clean up a bit in the next couple of days!

**Comment by jippi** [comment]
@vancluever can you move it to a PR, then I'll give it a look :)

**Comment by jippi** [comment]
@vancluever I've done some exposting of nomad-server config to the UI in this commit; i wonder how close it matches your settings :) 

https://github.com/jippi/hashi-ui/commit/ead8e36a3e38aec58e6782509e9b3d80e20fab10

**Comment by vancluever** [comment]
Nice! It matches very close, I like how you have organized the variables over what I have right now for sure.

One thing that i think we will need to change when I merge in my proxy stuff will be to make sure that the backend serves up the config for any URL ending in `/config.js`. This is because `'src', '//' + NOMAD_ENDPOINT + '/config.js'` won't necessarily be a predictable endpoint if we are proxying based on path (so now the URL becomes `http://localhost/nomad/config.js` instead of say, `http://localhost:3000/config.js`, and then possibly `http://localhost/nomad/cluster/config.js` say for example if the UI is reloaded).

Glad you found some other uses for this :) I'll adapt my code to accommodate this and put in the PR, hopefully tonight!

**Comment by jippi** [comment]
nice, looking forward to review it @vancluever ! :)

**Comment by vancluever** [comment]
OK, PR incoming now.

A few things to note but I'll note them in the PR text.

**Comment by jippi** [comment]
Closing as PR is now open :)
