### ISSUE TITLE
Table glitch in client properties

### ISSUE THREAD

**Issue by hynek** [jippi/hashi-ui#162]
I think this is best explained with a screenshot:

![2016-12-16 at 12 33](https://cloud.githubusercontent.com/assets/41240/21261465/e5a90b06-c38b-11e6-9410-5912c7c30e55.png)

I guess you forget to fill out the “drain” field so “HTTPAddr” goes up.

Also a little bit of spacing beneath NodeClass would be nice. :)

**Comment by jippi** [comment]
Thanks! :) 

What browser do you use - and operating system?

**Comment by hynek** [comment]
Safari Version 10.0.2 (12602.3.12.0.1) / macOS Sierra 10.12.2.
