### ISSUE TITLE
UI/UX improvements ideas

### ISSUE THREAD

**Issue by itatabitovski** [jippi/hashi-ui#164]
- In /servers the "Leader" column should have check mark only for the leader. The rest of the servers should not have any symbols. Currently they have a red X which next to the green check mark look like they are not healthy...

- In /clients "Status" column would be friendlier and more obvious to have colored text indicating the status. Having green check mark looks like there are only two options for status. It can be something like ready(green), initializing(blue), and so on...

**Comment by jippi** [comment]
Done!
