### ISSUE TITLE
Truncated output in task state

### ISSUE THREAD

**Issue by multani** [jippi/hashi-ui#165]
The output for the detailed allocation status of a task is truncated and there's no way (AFAIK) to expand it.

See the attached screenshot for example:

![screenshot from 2016-12-19 11-34-52](https://cloud.githubusercontent.com/assets/65311/21309737/b8589f9e-c5df-11e6-842e-ae7cf75e577a.png)

It's a pity because the interesting part is actually the truncated part :)

**Comment by jippi** [comment]
haha, nice, let me give it a look :)

**Comment by multani** [comment]
BTW, I used this job to trigger it (forgot to attach it in the original bug report):

```
job "test" {
    region = "default"
    datacenters = ["default"]
    priority = 1

    type = "service"

    update {
        stagger = "10s"
        max_parallel = 2
    }

    group "green" {
        count = 1                                                                                                                                                                                                                                                               

        restart {
            interval = "1m"
            attempts = 2
            delay = "15s"
            mode = "delay"
        }

        task "test" {
            driver = "docker"

            config {
                image = "non-existing-img"
            }
            resources {
                cpu = 200 # Mhz
                memory = 50 # MB
                network {
                    mbits = 10
                }
            }
        }
    }
}
```

**Comment by jippi** [comment]
@multani ha, perfect, was trying to get some long error in there :)

**Comment by jippi** [comment]
@multani should be fixed, let me know if `latest` docker tag works for you once its done building in ~8min time :)

**Comment by multani** [comment]
I'm keeping an eye on the Docker tag :)

**Comment by multani** [comment]
@jippi Awesome, that works great, thanks for the very quick fix! 👍
