### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by sheerun** [jippi/hashi-ui#166]
Hey,

The UI looks awesome! :) But does it support nomad when TLS is enabled? The readme only mentions NOMAD_ADDR while TLS support requires NOMAD_CACERT, NOMAD_CLIENT_CERT, and NOMAD_CLIENT_KEY

**Comment by jippi** [comment]
There is no TLS support at this time - a PR for this is more than welcome :)

**Comment by jippi** [comment]
@sheerun i've made a PR for TLS support, #167 , can you give it a try? :)

**Comment by jippi** [comment]
Closing issue as a PR is now open for further discussion
