### ISSUE TITLE
UI Doesn't Indicate All Region Leaders

### ISSUE THREAD

**Issue by andrewduch** [jippi/hashi-ui#168]
The server members page shows servers across all federated regions. However, it will only show the leader checkmark next to the leader of that local region. This differs from what `nomad server-members` shows which is it will indicate the leader for each region.

Note huge issue -- but was a bit confusing at first.

**Comment by jippi** [comment]
@andrewduch I don't have any cluster in prod with multiple regions and masters, so its probably a slight issue from that :) 

Same reason #130 currently is not implemented

**Comment by jippi** [comment]
@andrewduch #170 is the initial work for multiple region support - can you give it a test? :)

**Comment by jippi** [comment]
Fixed in https://github.com/jippi/hashi-ui/releases/tag/v0.12.0
