### ISSUE TITLE
Can't deal with DNS names

### ISSUE THREAD

**Issue by sheerun** [jippi/hashi-ui#169]
Hey,

I'm trying to connect to `NOMAD_ADDR` that happens to be a full domain instead of ip address. Unfortunately hashi-ui fails to resolve this address as shown on following gif:

http://www.giphy.com/gifs/l4JyMO35JgemumFmo

When using ip address instead of dns name, everything works OK.

This might be (but I only guess), that because you're using bare-metal docker image, and docker is unable to inject proper entry to /etc/resolv.conf so the Go's DNS resolver can handle name resolution: https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by sheerun** [comment]
Another more involved solution could be to use `export GODEBUG=netdns=cgo` when compiling go's binary.

**Comment by jippi** [comment]
@sheerun I'm currently building `latest` docker image now based on alpine instead, can you please take it for a spin? :)

**Comment by jippi** [comment]
Fixes https://github.com/jippi/hashi-ui/releases/tag/v0.12.1 for me :)
