### ISSUE TITLE
"getsockopt: connection refused", "Could not fetch nomad regions from API"

### ISSUE THREAD

**Issue by michaltrzesimiech** [jippi/hashi-ui#173]
Hey there, I'm running into this error trying to launch Docker containers with either version 0.12.0 or 0.12.1 ([logs](https://gist.github.com/michaltrzesimiech/ca621d7c06903b1759589988a8d47cd8)): `21:18:18.697 main.go:257 ▶ CRITI  Could not fetch nomad regions from API: Get http://127.0.0.1:4646/v1/regions?wait=60000ms: dial tcp 127.0.0.1:4646: getsockopt: connection refused`.

This error doesn't show up with v0.11.0, though I do bump into some other issues ([logs](https://gist.github.com/michaltrzesimiech/909db440b421ad8dd6b05c406c43d449)), which might or might not be related.

I followed [these instructions](https://github.com/jippi/hashi-ui/blob/master/README.md) with disabled firewall on two different environments for around 8 different setups with no success. I couldn't find a helpful thread running anywhere else, so I do hope that raising this here was a good decision. I'll be glad to help out with investigating this. 

Thanks!

**Comment by jippi** [comment]
@michaltrzesimiech hi! Do you have nomad running and listening on http://127.0.0.1:4646/ ? 

Otherwise you need to use `NOMAD_ADDR` `-nomad. address` to change the IP/hostname to match your environment 

Regarding your other issue, that seem to be because it uses port 8500 ? That's the Consul API HTTP UI/API port, not Nomad

Do you use network mode `host` for the docker container?

**Comment by michaltrzesimiech** [comment]
Hi and thanks for helping me out @jippi. 

I did use NOMAD_ADDR to match the address of the running instance of Nomad, which at that time was http://127.0.0.1:4646/. Looking through Nomad logs now, you're right that at least one of the problems comes from the side of Consul ([full log](https://gist.github.com/michaltrzesimiech/37ac5f5c33df5e683cd50d44b9c91e5c)):

```
2017/01/02 20:31:41.019358 [DEBUG] consul.syncer: error in syncing: 2 error(s) occurred:
* Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
* Get http://127.0.0.1:8500/v1/agent/checks: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
2017/01/02 20:31:44.973584 [ERR] client.consul: error reaping services in consul: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
```

I tried both Kitematic and `docker run -e NOMAD-ADDR=127.0.0.1:4647 -p 8000:3000 jippi/hashi-ui` to run the container with same result. Running it with `--net=host` produces [this result](https://gist.github.com/michaltrzesimiech/16d36c252eab6777ea647c84b5376abf). 

Any extra advice would be really helpful, but please feel free to direct me elsewhere or skip on the issue if I'm right to assume this isn't a Hashi-UI issue.
___
Scenario 1 (Xubuntu 16.04, Windows 7):
1. Run Nomad with `A:\devtools\nomad_0.5.2_windows_amd64\nomad.exe agent -dev`
Result: 2 syncing errors in Consul

2. Run Docker container with `docker run -e NOMAD-ADDR=127.0.0.1:4646 -p 8000:3000 jippi/hashi-ui`
Result: `main.go:257 ▶ CRITI  Could not fetch nomad regions from API: Get http://127.0.0.1:4647/v1/regions?wait=60000ms: dial tcp 127.0.0.1:4647: getsockopt: connection refused`

**Comment by jippi** [comment]
`--net=host` is a docker flag, so you need to put it with the docker flags

`docker run --net=host -e NOMAD-ADDR=127.0.0.1:4646 -p 8000:3000 jippi/hashi-ui`

The issue is outside of hashi-ui, but in your networking settings or docker :)

**Comment by michaltrzesimiech** [comment]
OK, so I tried to run it outside Docker and it works just fine. There seems to be a typo in [the docs](./hashi-ui-<os>-<arch> --nomad-enable) though: it only works for me with `./hashi-ui-<os>-<arch> --nomad.enable` instead of `--nomad-enable`.

Thanks for helping me out all the way through. :)
