### ISSUE TITLE
Auto Scaling / Deployment

### ISSUE THREAD

**Issue by gvenka008c** [jippi/hashi-ui#177]
Does hashi-ui supports auto scaling? Also can we use this for Blue/Green Deployments or Canary release?

**Comment by jippi** [comment]
@gvenka008c the UI today does not support any kind of auto-scaling... I'm working on an external prototype on this, that won't be part of the UI, but a separate binary that will integrate with the UI

Blue/Green deployments is something Nomad will support, but the UI will not (currently) automate or facilitate :)
