### ISSUE TITLE
Error: unable to fetch members: json: cannot unmarshal array into Go value of type api.ServerMembers

### ISSUE THREAD

**Issue by lumengxi** [jippi/hashi-ui#178]
Nice work!

When I ran this in Docker and point to a Nomad cluster, I got the following error message:
```
19:56:29.308 nomad_cluster_members.go:34 ▶ ERROR  watch: unable to fetch members: json: cannot unmarshal array into Go value of type api.ServerMembers
```

`Cluster CPU usage` and `Cluster RAM usage` are both blank, other charts are fine thou.

We are running on Nomad v0.4.1. If this is a breaking change on Nomad 0.5, it might worth mentioning this in the README.

**Comment by jippi** [comment]
@lumengxi the latest version only works with latest version of nomad, 0.5.x indeed

Until the UI is 1.x (and Nomad ditto), I'll try to keep it "latest version only" unless the effort to be backward compatible is trivial :)
