### ISSUE TITLE
CONSUL TOKEN WITH CONSUL_ENABLE

### ISSUE THREAD

**Issue by xudawei** [jippi/hashi-ui#181]
how to integration consul with consul token to hashi-ui  when CONSUL_ENABLE=1 .

**Comment by jippi** [comment]
Do you mean Consul ACL?

**Comment by jippi** [comment]
If you do, please take https://github.com/jippi/hashi-ui/pull/175 for a spin, that PR implements the feature, its not in mainline yet due to lack of someone testing it :)

**Comment by xudawei** [comment]
Yeah，it is . thanks a lot ,  i will take a look right now !
