### ISSUE TITLE
difference in CONSUL_ADDR and NOMAD_ADDR

### ISSUE THREAD

**Issue by shantanugadgil** [jippi/hashi-ui#182]
Hi,
Just wondering why the difference between the way CONSUL_ADDR is specified and NOMAD_ADDR
(one without the http and one with)

Regards,
Shantanu

_Awesome project, BTW!_

**Comment by jippi** [comment]
@shantanugadgil the NOMAD_ADDR is back from the days where I did not bother with TLS, where Consul API SDK handle the protocol part automatically depending on TLS configuration present or not :)
