### ISSUE TITLE
envhancement - show other stats 

### ISSUE THREAD

**Issue by OferE** [jippi/hashi-ui#183]
Would be great if in addition to cpu/memory we can see io stats and network.
thanks!

**Comment by jippi** [comment]
@OferE Its not something Nomad emits through the API at this time :( 

You can see the data available for hashi-ui here; https://www.nomadproject.io/docs/http/client-stats.html and https://www.nomadproject.io/docs/http/client-allocation-stats.html

would love to that those things, but until nomad exposes them, it's not going to be easy to do :(

**Comment by OferE** [comment]
thanks for the quick response. great project.
