### ISSUE TITLE
Show total amount of Memory and CPU for the currently allocated jobs

### ISSUE THREAD

**Issue by gokhansengun** [jippi/hashi-ui#184]
I have a setup which run on my dev box, test in the cloud and in the future prod in the cloud. I am defining resource limits for the tasks as below and setting the values according to the infrastructure it is currently running on.

```hcl
cpu = ${MEDIUM_1_CPU}
memory = ${MEDIUM_1_MEMORY}
```

Values between environments are defined with a multiplication factor.

Running a set of jobs in local environment and being able to see the currently reserved capacity will improve the capacity planning in the cloud because Nomad does not allow over provisioning of the resources.

Let's discuss if it is beneficial to have this Gadget in the Nomad dashboard for Hashi UI.

**Comment by jippi** [comment]
I think it could be interesting to have in the Cluster overview as a resource allocation (maybe as a 3rd color on the pie charts, showing "used", "allocated" and "available"

and maybe on each job have a box showing how much CPU / RAM / Network the job got allocated in total?

**Comment by aerickson** [comment]
+1 for this feature. Another project by the same name has something like this.

https://github.com/chuyskywalker/nomad-ui/blob/master/about/home.png

**Comment by jippi** [comment]
Done in `0.20.x` and `master`
