### ISSUE TITLE
Integrate with log backends (elasticsearch, graylog and more)

### ISSUE THREAD

**Issue by jovandeginste** [jippi/hashi-ui#188]
We ship our logs to an Elastic Search cluster; the logs are not available on the docker servers for nomad to collect (and thus for hashi-ui to show)

It would be nice if hashi-ui could either query an ES and show the log messages from there integrated in the ui, or (perhaps as a first step) link to an external location where the logs can be found, preferably parameterized url so you can point it directly to some kibana link showing what you need/want.

**Comment by josegonzalez** [comment]
I would prefer a parameterized link, as there are some of us who do not use the ELK stack, and instead use something like Graylog or an external service.

**Comment by jippi** [comment]
I'm for a parameterized link as well, and maybe backend specific drivers for fetching the logs, for closer integration

**Comment by burdandrei** [comment]
@jovandeginste do you guys run the collector in each group?

**Comment by jovandeginste** [comment]
@burdandrei what collector and what group?

**Comment by burdandrei** [comment]
@jovandeginste log collector  in nomad group, as it's written in nomad documentation.

**Comment by jovandeginste** [comment]
@burdandrei I'm not sure I fully understand, but here is how it's configured: the docker hosts have the journald logging driver as part of the daemon startup, and every nomad job has this snippet:
```hcl
[...]
        logging {
          type = "journald"
        }
[...]
```
(otherwise, nomad uses its default logging driver)

This means all logs are dropped into journald on the docker host, and there a logstash ships the logs to an ES cluster (logs are available locally for some period, until they are rotated)

**Comment by burdandrei** [comment]
@jovandeginste  docker is good, but we run a lot of exec =)

**Comment by alxark** [comment]
I would like to see an API for streaming logs from 3rd party systems to hashi-ui. I think API should have following functions:
1. support for real-time log streaming from log backends ( like elasticsearch) to hashi-ui server via websocket or any other type of persistent connection
2. support for some kind of query to filter output data
3. API to fetch supported filtering options ( for example information about ES filtering or some other backends).

API should be passed via ENV options and probably should be implemented as additional small service.

**Comment by josegonzalez** [comment]
@alxark that sounds like a completely separate project then, no?

**Comment by alxark** [comment]
API service? Absolutely yes. But API client should be implemented on hashi-ui side. I think it might be at least 2 drivers on start: 
* elasticsearch
* plain text syslog
I can implement such service but i need at least some small API specification to begin.
P.S. currently i need ES driver for one of my nomad installations

**Comment by jippi** [comment]
will not happen any time soon (if ever)
