### ISSUE TITLE
Read only does not seem to work as expected

### ISSUE THREAD

**Issue by jovandeginste** [jippi/hashi-ui#189]
I love hashi-ui as a way to visualize the workload on our nomad infrastructure; I want our devs to use it to see what their jobs do. However, I don't want them to be able to control jobs from there. So the read only options is very useful.

While testing, it does not seem to do anything, however. I added these ENV vars in the docker container:
```
NOMAD_READ_ONLY   = 1
NOMAD_ENABLE      = 1
```

and the container starts with this as (partial) output:

```
20170118 09:55:02.113	08:55:02.106 main.go:81  INFO  | log-level       	: info                                               |
20170118 09:55:02.114	08:55:02.106 main.go:89  INFO  | nomad-enable     	: true                                               |
20170118 09:55:02.115	08:55:02.106 main.go:91  INFO  | nomad-read-only       : Yes                                                |
```

But I can still stop running jobs, increase/decrease the count of a running job, and edit jobs. Is there something wrong with the flag parsing?

**Comment by jippi** [comment]
Fixed.. should land in master docker image in 5min time
