### ISSUE TITLE
Non-ascii characters don't display correctly

### ISSUE THREAD

**Issue by sethvargo** [jippi/hashi-ui#197]
It's possible to insert am emoji or non-unicode character into Consul's KV store (and it handles it well), but the hashi-ui fails to display it. Instead, it displays as s different unicode character, and then, when updating, it appends to itself.

![ezgif com-ae6a71fb3b](https://cloud.githubusercontent.com/assets/408570/22529273/aaa4c6e2-e88b-11e6-9aaf-9e93603ef057.gif)

**Comment by jippi** [comment]
I'll give it a look today :)

**Comment by jippi** [comment]
Fix should be in master now, give it 5min and the docker image should be up-to-date :)

**Comment by sethvargo** [comment]
Thanks!
