### ISSUE TITLE
Documentation for starting in docker is incorrect (out of date?)

### ISSUE THREAD

**Issue by rusterholz** [jippi/hashi-ui#201]
In the README it clearly states:

> Run the following command to start a webserver that will serve the application.
> `docker run --net=host -e NOMAD_ADDR=... -p 8000:3000 jippi/hashi-ui`

However, using the `latest` tagged image as of the time this issue was written, that command fails with the following log message:

`17:11:20.269 main.go:119 ▶ CRITI  Please enable at least Consul (--consul-enable) or Nomad (--nomad-enable)`

Can the README be updated with correct instructions for passing this flag through to the docker container? Thanks!

**Comment by lfarnell** [comment]
The command should just be ```docker run --net=host -e NOMAD_ADDR=... -p 8000:3000 jippi/hashi-ui --nomad-enable --consul-enable``` if you were running both nomad and consul.

I will update the docs for future users!

**Comment by rusterholz** [comment]
Thanks so much!

**Comment by automaticgiant** [comment]
if using net=host, then port publish is moot/erroneous?
and what is the reason for net=host?
from docker, it seems to run fine in default network mode.
