### ISSUE TITLE
Consul filter to show only failed services

### ISSUE THREAD

**Issue by Bullz3y3** [jippi/hashi-ui#202]
It would be nice to have this feature so we can utilize this a monitoring platform. This is already there in official consul-ui

**Comment by jippi** [comment]
@Bullz3y3 yeah, that seems like a good idea - long term i would love to have a dedicated dashboard for Consul showing generic cluster health information

**Comment by Bullz3y3** [comment]
@jippi sounds great. Currently I have replaced nagios with consul-ui and consul-alerts what I'm missing is above feature and a dedicated dashboard something like Uchiwa would be awsome

**Comment by jippi** [comment]
@Bullz3y3 in a few this should be in the master build (`latest` docker image)

![image](https://cloud.githubusercontent.com/assets/22841/22922860/944decd4-f29f-11e6-9615-0e032d221433.png)
