### ISSUE TITLE
Fail to parse Ipv6 leader address

### ISSUE THREAD

**Issue by seeder** [jippi/hashi-ui#207]
I have just tried it against my nomad system running entirely over IPv6 and I can see that hashi-ui has these errors in the log:

`[31m22:22:38.966 nomad_cluster_members.go:34 ▶ ERROR [0m watch: unable to fetch members: Failed to parse leader: [2001:111::1]:4647`

**Comment by jippi** [comment]
What version of hashi-ui ? can you please retry with the latest version? (`latest` tag)

**Comment by seeder** [comment]
Hi,

I'm running it via nomad , and using the job example you have in the repo. 
docker images lists is as : 
```
jippi/hashi-ui              latest              2b095e6e82ef        35 hours ago        35.3 MB
```

Running `/hashi-ui -test.v`
says 
```
(46) 2017/02/19 19:29:47.597115 {"level":"info","msg":"application created","context":{"app":"hashi-ui","enabled":false,"version":"1.5.0"}}
```

**Comment by seeder** [comment]
And  yes, about 100% of errors I find in GoLang apps related to IPv6 is authors assumption about using legacy internet protocol the v4.

Hope you can do some Go magic!

**Comment by ognemuh** [comment]
Yesterday, my fix was commited to master, and docker latest image already support ipv6 leader. Should we close this bug ? :)

**Comment by jippi** [comment]
Yep! :) thanks a bunch, if #204 is fixed this week too, i'll cut a new release with both fixes in
