### ISSUE TITLE
Support multiple consul/nomad clusters

### ISSUE THREAD

**Issue by josegonzalez** [jippi/hashi-ui#210]
In some setups, there is a consul cluster for different environments/regions. Ideally, one could swap between each cluster via a UI element, allowing deployers to avoid setting up multiple installations for their infrastructure.

Perhaps a comma-separated list of addresses can be set?

**Comment by jippi** [comment]
I would probably run a hashi-ui instance per cluster, rather than one ui instance talking to all of them. But willing to discuss potential multi-cluster mode

**Comment by josegonzalez** [comment]
Closing, as following the convention of one instance per cluster is fine for me :)
