### ISSUE TITLE
feature request: <head><title> changes depending on app (and env)

### ISSUE THREAD

**Issue by aerickson** [jippi/hashi-ui#211]
I'm not sure how to determine the 'env'. The IP of the serving host could be displayed (envs usually have unique subnets). It could just be a CLI option also.

Changing the favicon in consul mode would be cool too.

Use case: I have 4 hashi-ui tabs's up in my browser usually. 2 nomad UIs (1 for each environment) and 2 consul UIs. It's hard to see which tab is for which service/env.

**Comment by jippi** [comment]
I like it :)

**Comment by lfarnell** [comment]
I think a CLI option would be the most friendly. @jippi is it currently possible to pass arguments to the webpackplugin? I can see a PR if its not that hard

**Comment by jippi** [comment]
if anyone want to take a stab at this; https://github.com/nfl/react-helmet would probably be the way to go

**Comment by aerickson** [comment]
Thanks. That's where my research stopped (I wasn't sure how to get the
image packaged).


-------------------------------------------------------------------------------------------
You should follow me on Twitter at http://twitter.com/ajerickson.

On Fri, Mar 17, 2017 at 3:42 AM, Christian Winther <notifications@github.com

**Comment by jippi** [comment]
This is available in 0.16.0 :)
