### ISSUE TITLE
Unable to launch UI

### ISSUE THREAD

**Issue by ptarpan** [jippi/hashi-ui#214]
Hi, 
I am unable to launch the hash-ui locally. I followed the recommend steps but when running `make -j build` am getting the following: 

`
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j -C backend build
Installing github.com/kardianos/govendor
=> Running go fmt
=> Running go tool vet -all ./actions.go ./config.go ./consul.go ./consul_actions.go ./consul_cluster.go ./consul_config.go ./consul_connection.go ./consul_hub.go ./consul_region.go ./main.go ./nomad.go ./nomad_actions.go ./nomad_cluster.go ./nomad_cluster_members.go ./nomad_config.go ./nomad_connection.go ./nomad_hub.go ./nomad_region.go
Installing github.com/jteeuwen/go-bindata/...
Installing github.com/elazarl/go-bindata-assetfs/...
=> installing go-ps library...
go get github.com/mitchellh/go-ps
=> govendor sync...
govendor sync
=> building backend ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j /Users/user/Documents/gocode/src/hashi-ui/backend/build/hashi-ui-darwin-amd64
mkdir -p /Users/user/Documents/gocode/src/hashi-ui/backend/build
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j -C .. frontend
=> building frontend ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j -C frontend build
=> install frontend
yarn install --mutex file
make[4]: yarn: No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [frontend] Error 2
make[2]: *** [bindata_assetfs.go] Error 2
make[1]: *** [build] Error 2
make: *** [backend] Error 2
`

Am I doing something wrong? FYI, once I have this working on my dev env locally, I will be running this from an existing cluster.

**Comment by jippi** [comment]
as per the [dev instructions](https://github.com/jippi/hashi-ui/blob/master/DEVELOPMENT.md) you need yarn in your path too

`yarn: No such file or directory`

**Comment by ptarpan** [comment]
Thanks. Made some progress. Here's what I see now: 

`
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
✨  Done in 72.68s.
=> packaging assets ...
go-bindata-assetfs -prefix ../frontend ../frontend/build/...
=> building /Users/user/Documents/gocode/src/hashi-ui/backend/build/hashi-ui-darwin-amd64 ...
GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 govendor build -o /Users/user/Documents/gocode/src/hashi-ui/backend/build/hashi-ui-darwin-amd64
vendor/github.com/hashicorp/nomad/nomad/job_endpoint.go:4:2: cannot find package "context" in any of:
	/Users/user/Documents/gocode/src/hashi-ui/backend/vendor/context (vendor tree)
	/Users/user/.gvm/gos/go1.6.3/src/context (from $GOROOT)
	/Users/user/Documents/gocode/src/context (from $GOPATH)
Error: exit status 1
make[3]: *** [/Users/user/Documents/gocode/src/hashi-ui/backend/build/hashi-ui-darwin-amd64] Error 2
make[2]: *** [build] Error 2
make[1]: *** [backend] Error 2
make: *** [rebuild] Error 2
`

**Comment by jippi** [comment]
as per the [dev instructions](https://github.com/jippi/hashi-ui/blob/master/DEVELOPMENT.md) you need Go 1.7 (1.7.3) - never tried on 1.6.x

**Comment by ptarpan** [comment]
Thanks again @jippi . I will give that a shot as time permits and let you know.
