### ISSUE TITLE
Fall back from websockets

### ISSUE THREAD

**Issue by Ashald** [jippi/hashi-ui#215]
Websockets cannot be used via proxies [easily]. It'd be nice if Hashi-UI could fall-back to long polling from web sockets so that it can be used via an HTTP proxy.

**Comment by jippi** [comment]
This is nothing something I'm planning for, its quite a change 

If someone want to add this support, and if it doesn't add a lot of new complexity to the code, I'm fine with the addition :) 

Most proxies can rather easily upgrade and proxy websockets in my experience, so the problem doesn't seem big enough to require a huge complexity add-on in the code base - but I'm more than open to implementation proposals

**Comment by Ashald** [comment]
I'm using an SSH-based proxy quite often and it doesn't work with websockets. :(

**Comment by jippi** [comment]
Maybe https://www.npmjs.com/package/wstunnel could help?

**Comment by jippi** [comment]
Closing as this is not going to happen unless someone contributes :)
