### ISSUE TITLE
Issue with CPU load when hashi-ui is connected

### ISSUE THREAD

**Issue by madshaave** [jippi/hashi-ui#216]
We have just set up a new installation of Nomad/Consul server, and connect the hashi-ui to this node with the following params: --consul-enable --nomad-enable --nomad-address http://x.x.x.x:4646 --consul-address x.x.x.x:8500
Now, once we open the UI, the CPU for the nomad process on the server peaks (40-50%), and stays that way until we shut down the hashi-ui process. Just closing the browser is not enough.
The Nomad and Consul server is running on Windows 2016 server. We have attempted to run the hashi-ui on the same host as the nomad and consul, and also on a separate host, but same result. The CPU for hashi-ui also seems strangely high.
Is this a known issue?
Regards,
Mads

**Comment by jippi** [comment]
do you run any proxy between consul/nomad and hashi-ui?

**Comment by madshaave** [comment]
No, there is no proxy between them.

**Comment by jippi** [comment]
Can you please increase log level and include nomad/consul/hashi-ui log to the issue?

and try with just one of them.

also, is there anything like AWS LoadBalancer or something - or is it a 100% direct, no middle-man connection?

**Comment by jippi** [comment]
Also, is the nomad cluster empty, or does it have some jobs / clients available?

**Comment by madshaave** [comment]
I will try to get the logs asap.
There are no jobs running yet. Not even a client agent, only the server.
