### ISSUE TITLE
Sensitive data from Raw JSON (Env:object)

### ISSUE THREAD

**Issue by Wintermute1** [jippi/hashi-ui#217]
The envs contain sensitive data, is there a possibility of adding an option to mask this data?

For example the raw JSON which is exposed here -http://localhost:3000/nomad/europe/jobs/x/groups?taskGroupId=x

**Comment by jippi** [comment]
As mentioned in Gitter, this would have to be done server side (in Go) to prevent it being sent on the wire in general.

I don't have this use-case myself, and not sure to what extent it would work, would it be env{}, meta{}, (docker) labels{} etc

Feel free draw up a draft / RFC for it :)

**Comment by jippi** [comment]
Fixed in #225
