### ISSUE TITLE
can't access dashboard on ios 

### ISSUE THREAD

**Issue by leemhenson** [jippi/hashi-ui#227]
Hi. From my laptop I can access our hashi-ui dashboard fine. But via Safari, Chrome and Firefox on my iPhone 6, I get "Unable to connect to the backend...Something bad and unexpected happened."

Is this some missing feature on mobile browsers? Websockety?

**Comment by jippi** [comment]
I'm using hashi-ui daily on my iOS devices in Safari and Chrome 

What version are you using? any load-balancers or proxy between you and the hashi-ui ?

**Comment by leemhenson** [comment]
0.15.4. I'll check to see if what config is on our load balancer.

**Comment by leemhenson** [comment]
Ok, it looks like it's because the dashboard is protected by basic auth. Running devtools shows:

<img width="1239" alt="nomadscreencap2" src="https://cloud.githubusercontent.com/assets/515/24749953/fb756b5e-1abc-11e7-8d5e-8105f434f9bb.png">

I can log in via the safari basic auth popup, but I guess it's propagating that session through to the websocket connections?

**Comment by leemhenson** [comment]
Bit more info. The headers on the ws request include (replacing the key obvs):

```
Sec-WebSocket-Extensions:x-webkit-deflate-frame
Sec-WebSocket-Key:abcdefghijlmnopqrstuvwxyz==
Sec-WebSocket-Version:13
```

**Comment by jippi** [comment]
hashi-ui don't do any kind of auth, so there must be some proxy in-between you and he hashi-ui server if you see any kind of auth popups :)

**Comment by leemhenson** [comment]
Yes, it's our basic auth. The issue, _I think_, is that hashi-ui's websocket connections don't seem to be picking that context up from the browser.

**Comment by jippi** [comment]
What context do you mean @leemhenson ? is it a proxy issue #204 ?

**Comment by leemhenson** [comment]
Hi Jippi. So I've tried using a couple of modern Android devices and they work just fine. Checking the headers on those requests shows the `ws` requests include the `Authorization` header. The iOS `ws` connections do not. 

Unless you know of a way to do something like:

```js
var socket = new WebSocket(url);

socket.enlistIntoBrowserSession(); // <- magical made-up api that automatically adds Authorization headers

// ...
```

I guess we'll have to introduce a standard cookie-based auth mechanism into our stack, and take out this simple Basic Auth. That's assuming ios websockets even manage to get _cookies_ right.....

I guess this issue can be closed then?

**Comment by jippi** [comment]
Would love to have a fix in hashi-ui, or a work-around documented somewhere for it 

If you come up with something that works nicely, i would love to have it in the project :)

**Comment by jippi** [comment]
Not sure if http://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api would work :)

**Comment by leemhenson** [comment]
This is probably the issue: https://bugs.webkit.org/show_bug.cgi?id=80362

**Comment by jippi** [comment]
Closing at it seem to be a browser bug - if there is a work-around, a contribution for the fix is more than welcome
