### ISSUE TITLE
nomad log becomes huge when in debug mode.

### ISSUE THREAD

**Issue by toming90** [jippi/hashi-ui#228]
I have a nomad-ui(not hashi-ui, but I'm sure same thing will happen in hashi-ui ) running on my cluster. The nomad agent on cluster is in debug mode, which means nomad.log will record every requests it received. This seems cause a big issue that nomad log file becomes very very huge after two weeks of running(about 40G). 
I think this behavior is caused by the frequent polling in backend server. It kept sending requests to nomad agent every 10 seconds. 
I'm wondering if there is anyway to prevent this behavior. I'm now trying to terminate the frequent polling in backend, my idea is to let watchAllocs, watchJobs, watchNodes etc.. be triggered only when I click the tab button. Any ideas?

**Comment by toming90** [comment]
It seems the new hashi-ui log is much less than nomad-ui. Let me do more research on this.

**Comment by jippi** [comment]
keep me posted :)
