### ISSUE TITLE
Overview of client resource usage

### ISSUE THREAD

**Issue by memelet** [jippi/hashi-ui#229]
Something like the clients/stats view but for all clients in one page so we can see the big picture we be quite nice.

**Comment by jippi** [comment]
So you want a list of each client, and their individual resource usage? (cpu/ram/disk) ?

**Comment by memelet** [comment]
Or a combined (compressed) dashboard. Something that provides a quick view of how the clients are loaded all at once. 

Mesos shows the  allocated CPU vs actually used CPU for both client nodes and tasks on that node. Is that possible?

**Comment by jippi** [comment]
the UI today doesn't show allocated, but actual usage - so maybe it's actually showing what you expect it to already ? :)

**Comment by memelet** [comment]
Ok, but it's always nice to see both. It's hard to get memory and cpu allocations correct. Of course for memory you find out by the container being shutdown. But for cpu it's nice to know when the service (or node) is under or overallocated relative to actuals.

**Comment by Xopherus** [comment]
@jippi having resource usage stats for individual clients would be super helpful for sizing containers

**Comment by jippi** [comment]
@Xopherus if you go clients > click on a client -> stats there should be individual stats, or not what you mean? :)

**Comment by Xopherus** [comment]
sorry i misspoke. i mean stats on a per job basis. that way i can validate that the resources i've allocated are not only sufficient for the job, but that i don't over allocate resources.

**Comment by jippi** [comment]
please do :) i would love to do job level stats too :)

**Comment by jippi** [comment]
both of these are done in master and should be in `0.20.0` :)

**Comment by iosven** [comment]
Sorry for asking this here, but where can I find the documentation regardinf the Stats in the Hashi-UI?

Especially interested in an explanation of the CPU stats "User" "System" "Used".
