### ISSUE TITLE
root directory Makefile doesn't work

### ISSUE THREAD

**Issue by toming90** [jippi/hashi-ui#230]
Hi, I do a vagrant up and run a "make" command in the root directory, it supposed to have a binary built, which include both backend and frontend according to wiki: https://github.com/jippi/hashi-ui/blob/master/DEVELOPMENT.md#building . But here I don't get anything build. The terminal output is:
```
vagrant@vagrant:~/work/src/github.com/jippi/hashi-ui$ make 
=> building frontend ...
make -j -C frontend build
make[1]: Entering directory '/home/vagrant/work/src/github.com/jippi/hashi-ui/frontend'
=> install frontend
yarn install --mutex file
yarn install v0.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 113.16s.
=> building frontend ...
yarn run build
yarn run v0.22.0
$ webpack --config webpack-prod.config.js -p --progress 
Hash: cd5321400a1df98b78c4  
Version: webpack 1.14.0
Time: 152008ms
                                               Asset       Size  Chunks             Chunk Names
                 static/main.c73b9ff91e32f0364f5b.js     2.1 MB       0  [emitted]  main
    static/main.28a838e382347fc6a534ad4c713a4f76.css    29.5 kB       0  [emitted]  main
             static/main.c73b9ff91e32f0364f5b.js.map    13.8 MB       0  [emitted]  main
static/main.28a838e382347fc6a534ad4c713a4f76.css.map    24.6 kB       0  [emitted]  main
                                         favicon.png  949 bytes          [emitted]  
                                          index.html    1.38 kB          [emitted]  
   [0] multi main 40 bytes {0} [built]
    + 1591 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Done in 153.88s.
make[1]: Leaving directory '/home/vagrant/work/src/github.com/jippi/hashi-ui/frontend'
vagrant@vagrant:~/work/src/github.com/jippi/hashi-ui$
```

**Comment by jippi** [comment]
@toming90 there is no actual target to build both frontend+backend, maybe just `make build` (which probably should be the default target)

**Comment by toming90** [comment]
@jippi I tried make build, and I get a backend binary in /backend/build. I tried to run the backend binary alone, without running "yarn start" in /frontend . It makes sense for me that it displays nothing in localhost:3333/nomad page because there is no frontend running. 
However, in Dockerfile, it adds backend binary to container and directly trigger it without any frontend command.

**Comment by lfarnell** [comment]
@toming90 What about running make -j build? This should build everything for you in one binary

**Comment by toming90** [comment]
@lfarnell  Same thing happened if run "make -j build".  It will build a binary in /backend/build, I run this binary alone without running "yarn start" in /frontend, nothing displays when I hit localhost:3333/nomad . I checked there is no /build folder in root directory. 
Does that work well on your machine?

**Comment by lfarnell** [comment]
@toming90 i think i know where you have have gone wrong. So when you do make -j build, the front-end and back-end should get bundled together into the hashi-ui binary. Now where your going wrong is that your trying to access the react dev port(3333) instead of the server port(3000). Just for certainty, run make clean, then make dist-clean and finally make rebuild. After all of these complete, run the hashi binary and access the UI via localhost:3000. This should work for you :) Let us know how it goes!

**Comment by toming90** [comment]
@lfarnell , that works! :)  The port number should be 3000. Thank you so much!
