### ISSUE TITLE
Support Consul SSL and Custom Certs

### ISSUE THREAD

**Issue by sethvargo** [jippi/hashi-ui#234]
At present, there doesn't appear to be support for custom certs, or SSL addresses. You can read more about [Consul encryption and TLS here](https://www.consul.io/docs/agent/encryption.html), but support would require:

- Allowing https:// URLs (currently they are rewritten to http://https://127.0.0.1:8500)
- Support `CONSUL_CAPATH`, `CONSUL_CLIENT_CERT`, and `CONSUL_CLIENT_KEY`

**Comment by jippi** [comment]
@sethvargo do you run `latest` tag for these cases or a tagged version?

**Comment by sethvargo** [comment]
Hi @jippi 

I thought that too, but something weird is going on. I was able to use the envvars to get past the url rewriting, but I'm still getting 'bad tls cert' on every request 😦

**Comment by jippi** [comment]
@sethvargo would you be able to cook up a new folder in https://github.com/jippi/hashi-ui/tree/master/scripts with a consul node with tls i can test with? :)

**Comment by sboily** [comment]
Hello, i did a test and it works with this command.

> CONSUL_HTTP_TOKEN=token CONSUL_HTTP_SSL_VERIFY=false CONSUL_HTTP_SSL=true ./hashi-ui-linux-amd64 --consul-enable --consul-address 10.41.0.2:8500

**Comment by jippi** [comment]
@sboily sweet! can you document that in a PR ? :)

**Comment by sboily** [comment]
Yes.

**Comment by sethvargo** [comment]
Ah okay - those envvars work. Thanks!

**Comment by marcjay** [comment]
There is an actual issue here, the version of the Consul API used predates [this commit](https://github.com/hashicorp/nomad/commit/78af6000704860e81edeb4b21199ee3f3ca657e9#diff-40cd17322eac38db030c42465d64597b) which allowed for the API to retrieve CONSUL_CACERT, CONSUL_CLIENT_CERT and CONSUL_CLIENT_KEY environment variables.

I've opened PR #256 to fix this

**Comment by jippi** [comment]
Merged, thank you!
