### ISSUE TITLE
Add /health endpoint

### ISSUE THREAD

**Issue by sethvargo** [jippi/hashi-ui#235]
The current health check is just to hit `/`, but that just guarantees that the file server is running; it does not check that hashi-ui can connect to the various backends and return data.

**Comment by ericwestfall** [comment]
Happy to implement something for this @jippi, if you'd like a hand ...

**Comment by jippi** [comment]
@ericwestfall would be amazing ! :)

**Comment by ericwestfall** [comment]
This would be quite useful, I'll try and throw something together.

**Comment by pvandervelde** [comment]
@ericwestfall Any progress on this item. We're currently trying to put HashiUI behind fabio but that needs a running health check. We can just point to the `/` address but it would be nice to have a useful health check :)

**Comment by jippi** [comment]
`/_status` should now implement this ( in master )
