### ISSUE TITLE
nomad_connection.go - app crashes when keepalive writing to closed channel 

### ISSUE THREAD

**Issue by ognemuh** [jippi/hashi-ui#236]
``panic: send on closed channel``
``goroutine 1640454 [running]:``
``panic(0xc8f1a0, 0xc420ba2810)``
 `` /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
main.(*NomadConnection).keepAlive(0xc4202b2c60)``
  ``/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_connection.go:302 +0x238
created by main.(*NomadConnection).Handle``
 `` /home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_connection.go:280 +0x43``

Seems like nomad server had a connection problem, but we shouldn't write into closed channel.

**Comment by jippi** [comment]
what version of hashi-ui do you run? latest?

**Comment by ognemuh** [comment]
Yep, pull and run latest docker tag.
