### ISSUE TITLE
use ?stale=true in the request to the nomad servers

### ISSUE THREAD

**Issue by lolovarga** [jippi/hashi-ui#238]
We noticed that hashi-ui generates a lot of network traffic between the nomad servers.
Because you hit the endpoint without allowing stale reads, the server will forward the request to the the leader. You can enable stale reads which will return the data from the server that is hit with ?stale=true. 
Nomad docs that describe this behaviour: https://www.nomadproject.io/docs/http/#consistency-modes

**Comment by jippi** [comment]
That seems like a nice improvement, a new flag, should be default ON imo, and allowing people to turn it off if they can't accept potential stale data

Are you able to PR the required changes? :)

**Comment by lolovarga** [comment]
I could, do you have to give me permissions to push a new branch to your repo? This is what I get:
`✔ ~/src/hashi-ui [AllowStale L|✔]
11:30 $  git push --set-upstream origin AllowStale
ERROR: Permission to jippi/hashi-ui.git denied to lolovarga.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
