### ISSUE TITLE
Feature Request: Multiple consul and nomad addresses

### ISSUE THREAD

**Issue by code-eater** [jippi/hashi-ui#257]
I'm running hashi-ui and i really like it. 
It gives me a great overview of everything running in my cluster. 
So my problem is that i don't want to deploy hashi-ui in my cluster on nomad (because of security). So i created a separate minimal vm where hashi-ui is running on. But at the moment i can only connect hashi-ui to one node in the cluster. 

If i maintain this node and take it offline / reboot / whatever i can't see the status of the cluster anymore. So it would be cool if possible to have fallback servers in the configuration like:

`
./hashi-ui-linux-amd64 
--nomad-enable 
--consul-enable 
-listen-address=x.x.x.x:3000 
-nomad-addresses=http://x.x.x.x:4646,http://y.y.y.y:4646,... 
-consul-addresses=x.x.x.x:8500,y.y.y.y:8500,...
`

**Comment by jippi** [comment]
I think it could work, though honestly it's not a need i have myself, so probably won't implement it any time soon. A contribution with the required changes could be accepted. 

A hack around it would be to connect to a CNAME which your consul cluster keep in sync to a healthy backend node - or simply query consul catalog for IPs that are healthy as nomad/consul servers and restart hashi-ui with one of those IPs when the IP changes

**Comment by code-eater** [comment]
thanks for that workaround. the restart way is how i do it currently. I just thought perhaps there is a better way to do it. Thanks for your reply...

**Comment by jippi** [comment]
Closing as the workaround seem good enough for a narrow use-case
