### ISSUE TITLE
Allocations -> Allocation page transition is slow

### ISSUE THREAD

**Issue by thomas-mcdonald** [jippi/hashi-ui#262]
Still root causing but thought I'd file an issue to note the page transition from the allocations table to an individual allocation is super slow on our instance, five-ten seconds.

Looking at profiling, looks like a _lot_ of event handlers are being removed as the allocations table gets unmounted.

**Comment by thomas-mcdonald** [comment]
`react-append-to-body` takes ~200ms to clean up (while running the profiler) for each instance of AppendedReactTooltip. This cost is contained in [deleteElement](https://github.com/jpgorman/react-append-to-body/blob/master/src/component-registry.js#L20).

<img width="310" alt="screen shot 2017-07-15 at 10 05 43 pm" src="https://user-images.githubusercontent.com/197928/28242674-d641a2a8-69a9-11e7-95af-c0f26acea249.png">

Given the allocations table has 35 entries and there are two tooltips in each entry, this is a baseline cost of `35*2*200 = 14000ms` to tidy up the appended elements. Will see if there is a CSS-based fix along similar lines to #252 that is less expensive.

**Comment by jippi** [comment]
I've noticed this too, not sure what change caused it :o

**Comment by jippi** [comment]
found the problem :)

**Comment by thomas-mcdonald** [comment]
That's pretty similar to the fix approach I was working on - `FormatTime` probably also needs to be switched away from the `AppendedReactTooltip` implementation.

**Comment by jippi** [comment]
:) i packed my fix into a general update of some of the UI setup, since nomad 0.6 will have deployments, so need more space for that in the menu :)
