### ISSUE TITLE
Improve the task state history messages

### ISSUE THREAD

**Issue by multani** [jippi/hashi-ui#268]
This is the output as reported by the Nomad CLI when requesting the information for an allocation:

```
$ nomad alloc-status 28109b45
...

Recent Events:
Time                    Type            Description
07/19/17 16:19:34 CEST  Not Restarting  Policy allows no restarts
07/19/17 16:19:34 CEST  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
07/19/17 16:19:32 CEST  Started         Task started by client
07/19/17 16:19:09 CEST  Driver          Downloading image XXX
07/19/17 16:19:09 CEST  Task Setup      Building Task Directory
07/19/17 16:19:09 CEST  Received        Task received by client
```

And what's being displayed by Hashi-UI:
![screenshot from 2017-07-19 16-26-45](https://user-images.githubusercontent.com/65311/28372192-4ee2f278-6c9f-11e7-8ca2-3f55abf798b0.png)

Ideally, Hashi-UI should reuse this code from [the `alloc-status` command](https://github.com/hashicorp/nomad/blob/master/command/alloc_status.go#L279), but this particular piece of code is not exported from the module and is a bit too connected to the CLI tool.

I'm not sure what's the proper way to do that in the Go community? Should I make a PR against Nomad to move the `switch` code into a dedicated function that can be exported so it can be reused here?

**Comment by jippi** [comment]
oh, its probably missing a few new fields in the driver output - its a pure JS fix to do that

I guess you mean the missing Message/Reason values?

**Comment by jippi** [comment]
The problem is here https://github.com/jippi/hashi-ui/blob/master/frontend/src/components/AllocationInfo/AllocationInfo.js#L81-L90 

There are probably a new field in the API with those new keys/descriptions 

So hit the nomad API endpoint for your allocation and see what keys hold the different descriptions and add them in `OR` / `||` mode to the list

**Comment by multani** [comment]
That would work for some (maybe most) events, but there will still be noticeable difference between the command line tool and what the API returns.

For example, consider the following event as returned by the API (this event is not really interesting by itself, but hopefully shows the initial problem):
```json
                {
                    "DiskLimit": 0,
                    "DownloadError": "",
                    "DriverError": "",
                    "DriverMessage": "",
                    "ExitCode": 0,
                    "FailedSibling": "",
                    "FailsTask": false,
                    "KillError": "",
                    "KillReason": "",
                    "KillTimeout": 0,
                    "Message": "",
                    "RestartReason": "",
                    "SetupError": "",
                    "Signal": 0,
                    "StartDelay": 0,
                    "TaskSignal": "",
                    "TaskSignalReason": "",
                    "Time": 1500551221714132898,
                    "Type": "Received",
                    "ValidationError": "",
                    "VaultError": ""
                },
```

The CLI would display this as ["Task received by client"](https://github.com/hashicorp/nomad/blob/master/command/alloc_status.go#L303) although there's no message in any of the field returned here.

Another example would be the `SiblingFailed` event type, [which is worded that way in the CLI tool](https://github.com/hashicorp/nomad/blob/master/command/alloc_status.go#L372-L377).
Reading this code, I guess the `FailedSibling` message field is very succinct, and that would be reflected in Hashi-UI events panel.
