### ISSUE TITLE
HTTPS configuration for Hashi-UI does not support ENV variables

### ISSUE THREAD

**Issue by marcjay** [jippi/hashi-ui#270]
The ENV vars: HTTPS_ENABLE, SERVER_CERT and SERVER_KEY should be equivalent to the cli flags but they have no effect.

This should supposedly work, but from looking at the code, I think this was missed out. I'll submit a PR shortly

**Comment by jippi** [comment]
What version of hashi-ui have you tested this with? and is it for nomad or consul?

**Comment by marcjay** [comment]
It's the latest version. I can see the problem - this PR #258 added support for CLI flags, but it didn't add the same changes to ParseAppEnvConfig
