### ISSUE TITLE
Windows executable does not contain .exe extension

### ISSUE THREAD

**Issue by lfarnell** [jippi/hashi-ui#273]
User from Gitter mentioned that the file he was downloading from GitHub releases wasn't working with Powershell Expend-Archive cmdlet. After looking at the file, it is indeed an executable file. The problem is that the file does not contain the .exe extension needed in order to run. It looks like this is related to Travis and how it builds the windows binary

**Comment by AstralDestiny** [comment]
If I'm reading this correctly you can just rename the file to have the .exe at the end and it will work fine.

**Comment by jippi** [comment]
Correct, a rename should do the trick

a PR is welcome to fix it, closing for now
