### ISSUE TITLE
FEATURE: Display Nomad job deployment information

### ISSUE THREAD

**Issue by jrasell** [jippi/hashi-ui#277]
The release of Nomad 0.6.0 brings the feature of deployments, and it would be lovely to display information about a job deployment history/status alongside the job information.

Initial thinking could be that deployments are displayed in two ways:
1. The jobs list page a column could be added stating the last deployment status
2. The job details page could gain a deployment tab, which details deployment history

I would be happy to take a bash at this if you're happy with that @jippi and would love any and all feedback.

**Comment by jippi** [comment]
i like both 1 +2 

but also think we need a dedicated /deployments page in the left menu to reflect https://www.nomadproject.io/api/deployments.html

**Comment by jippi** [comment]
Ideally we would have a job or deployment page to control promote/revert and all the other actions around the new APIs

**Comment by jrasell** [comment]
Yeah that makes sense; although I do try to avoid people running the UI in read/write mode.

**Comment by jippi** [comment]
I personally use it in both modes, depending on instance :)
