### ISSUE TITLE
websocket is not working on windows ie 

### ISSUE THREAD

**Issue by fkgre** [jippi/hashi-ui#285]
i tried but not working. below error.

WebSocket Error: Incorrect HTTP response. Status code 200, OK

this issue will happen http and websocket(ws) use same port.for example

http://localhost:8080/ 
ws://localhost:8080/

could you please give a option that set http and websicket port separately

**Comment by jippi** [comment]
What version of IE ?

**Comment by fkgre** [comment]
Hashi-UI version: 0.14.0
OS: Windows 2012 x64
IE version: 11.0.42

below are working fine
chrome: 59.0.3071
firefox:54.0.1

**Comment by jippi** [comment]
I don't use IE myself (on OSX) so will probably not spend time trying to fix this.. If it works in Firefox, Chrome, Safari and Edge, then I'll probably not spend too much time on a browser that is basically in legacy mode at this time :(

**Comment by jippi** [comment]
Closing the issue as IE11 is kinda old anyway and quirky
