### ISSUE TITLE
Edit Job modal window closes automatically

### ISSUE THREAD

**Issue by Goobs** [jippi/hashi-ui#286]
My hashi-ui instance works in Nomad cluster. After it's job restart yesterday Nomad fetched `:latest` tag from Docker hub and seems that it is broken. When I try to open 'Edit Job' modal and do some chances, it closes automatically after few seconds. For now I am forced to use old `v0.13.6` version. 

Docker image hash for broken version is `8d3fc71a8dae`

**Comment by danlsgiga** [comment]
Same here! Rolling back to 0.13.6

**Comment by jippi** [comment]
Should be fixed in master/latest now, please allow ~5min for the new docker image to be available
