### ISSUE TITLE
[rfe] update build process to use zip file

### ISSUE THREAD

**Issue by shantanugadgil** [jippi/hashi-ui#287]
Hi,
Would the following enhancements  be possible to the current build process of Hashi-UI:
* use zip file with version number in it
* .exe for the Windows' binary

This will ease the scripts that I (and I assume other folks too) have for downloading all the HashiCorp tools.

As of now only Hashi-UI is the exception 😀 

Regards,
Shantanu

**Comment by bgilner** [comment]
The workaround I use is:

1) download: https://github.com/jippi/hashi-ui/releases
2) regex to extract version with: <a\shref=""/jippi/hashi-ui/releases/download/v([^/]*)/hashi-ui-windows-amd64

**Comment by jippi** [comment]
Hi, i don't think I'm going to do this - as it would break other peoples expectation on how hashi-ui already works now :)
