### ISSUE TITLE
ipv6 not supported?

### ISSUE THREAD

**Issue by sholland** [jippi/hashi-ui#288]
# Listen Address complains about too many colons
./hashi-ui-linux-amd64 --nomad-enable --listen-address 2620:10d:c081:11::68
09:23:50.959 nomad.go:31 ▶ INFO  Starting handlers for region: global                                                            
09:23:50.959 nomad.go:50 ▶ INFO    -> Connecting to nomad
09:23:50.959 nomad.go:59 ▶ INFO    -> Starting resource watchers
09:23:50.959 main.go:122 ▶ INFO  Nomad client successfully initialized
09:23:50.960 main.go:208 ▶ INFO  Listening
09:23:50.960 main.go:218 ▶ CRITI  listen tcp: too many colons in address 2620:10d:c081:11::68

# Without any specification, it does not pick up the ipv6 address
./hashi-ui-linux-amd64 --nomad-enable
...
| listen-address        : http://0.0.0.0:3000
...

# More than willing to help fix this, but might need some pointers

**Comment by jippi** [comment]
Never tested with IPv6, nor do I have an environment with IPv6, so would need outside help maintaining that :)

**Comment by lfarnell** [comment]
I looked into this and a code change would be needed in order for gorilla mux to listen on an IPv6 address

**Comment by sholland** [comment]
I can definitely help with any testing. Just an fyi, In looking at more, it looks like if I omit the address it will listen on ipv6. Or if i specify the listen-address as 0.0.0.0:<port> , it will actually work with ipv6. 

 shollandadmin@prn-sholdev01:~$ netstat -anl | egrep -i 80                                                                         │·························
tcp6       0      0 :::80                   :::*                    LISTEN

So I can work with it as is. Probably can change to feature request of specifying the listen-address with the v6 address.

**Comment by sholland** [comment]
imma close this issue. I thought i tested using the listen-address [2620:10d:c081:11::68]:80 and it was failing, but I just ran again and it worked. Sorry for the trouble.
