### ISSUE TITLE
remember the job selection filters

### ISSUE THREAD

**Issue by shantanugadgil** [jippi/hashi-ui#289]
Version: v0.14.2

Could you add a feature so that the job selection filters can be remembered on the **Jobs** page.

Today, when I click somewhere else, say "Allocations", and come back to the **Jobs** page the selection filters are lost.

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
AWS EC2 console _absolutely_ remembers EC2 search filters based on TAGS, states, etc. In which case does it forget search filters ?

**Comment by jippi** [comment]
My point is that AWS only does it in some UIs, even within EC2 dashboard, and especially between different AWS services.. it was just an example, not a reason not to do it or not. 

As I said, I would need some discussion from the community wether this is desired or not :)

**Comment by jippi** [comment]
I'm closing this as there doesn't seem to be much interest in the issue at this time from the community :)

**Comment by shantanugadgil** [comment]
:sad
