### ISSUE TITLE
Task Stats

### ISSUE THREAD

**Issue by gauravyadav01** [jippi/hashi-ui#291]
Task Stats does not give the running task until you hover the mouse. When you refresh the browser , it again returns to 0  and it does not shows up until you hover the mouse.

**Comment by jippi** [comment]
Can you please explain the issue(s)  ? sounds like two distinct problems?

Please provide reproducible steps, browser info, hashi-ui version and steps needed to see the problem

**Comment by gauravyadav01** [comment]
Hi Christian, 
thanks for prompt reply.
Here are the screen shots 1 and 2. 
First screen shots is right after refreshing the browser.
Second screen shots is when you hover the mouse.

Browser : Google chrome Version 60.0.3112.90 (Official Build) (64-bit)
Browser: IE 11.0.44

hashui version : v0.14.2

log message -------------------
2017-08-14_16:14:46.96904 (19837) 2017/08/14 16:14:46.968354 {"level":"info","msg":"application created","context":{"app":"hashi-ui","enabled":false,"version":"1.9.0"}}

-----------------------------------




![task_stats_1](https://user-images.githubusercontent.com/12859625/29280694-4549d178-80ea-11e7-8bc4-d014b199f4dc.gif)
![task_stats_2](https://user-images.githubusercontent.com/12859625/29280695-454b2b86-80ea-11e7-9b39-f4b5bd5b384f.gif)

**Comment by aconte76** [comment]
Task Stats is also not well rendered on page:

Here a snapshot from my Chrome v.60.0.3112.101

![image](https://user-images.githubusercontent.com/12640737/29577622-64384c76-876c-11e7-8c12-a5d5eb780389.png)

**Comment by jippi** [comment]
Can you try the docker container `jippi/hashi-ui:pr-295` ? both master and `jippi/hashi-ui:pr-295` works for me 

Also, can you check the Console for any errors?

What version of hashi-ui do you run?
