### ISSUE TITLE
have job overview Allocation Status reflect latest deployment

### ISSUE THREAD

**Issue by hsmade** [jippi/hashi-ui#293]
When #277 is done, it would become possible to have a filter on the allocations used for the *Allocation Status* on the job overview page. This would then restrict the list of allocations to the latest deployment.

Currently, when doing lots of deploys, the *Allocation Status* bar gets filled up with failed and completed counts for allocations that have been replaced by others, in newer deployments.

**Comment by jippi** [comment]
I haven't bumped any infra to 0.6, but seems like the alloc api endpoint don't expose anything related to the deployment ( https://www.nomadproject.io/api/allocations.html )

So would probably be a new menu called 'deployments' where you can see the allocations belonging to each deployment ( https://www.nomadproject.io/api/deployments.html )

**Comment by hsmade** [comment]
No, sadly that is reversed in the api: https://www.nomadproject.io/api/deployments.html#list-allocations-for-deployment :(
