### ISSUE TITLE
Makefile:104: recipe for target 'govendor' failed              make: *** [govendor] Error 127

### ISSUE THREAD

**Issue by alliyaan** [jippi/hashi-ui#294]
$ sudo mkdir -p $GOPATH/src/github.com/skydive-project
$ sudo git clone https://github.com/skydive-project/skydive.git $GOPATH/src/github.com/skydive-project/skydive
$ cd $GOPATH/src/github.com/skydive-project/skydive
$ sudo make install

ali@ali-machine /src/github.com/skydive-project/skydive $ sudo make install
go get github.com/kardianos/govendor
/bin/govendor sync
make: /bin/govendor: Command not found
Makefile:104: recipe for target 'govendor' failed
make: *** [govendor] Error 127
help ..!

**Comment by lfarnell** [comment]
@alliyaan I believe you posted this to the wrong GitHub project.
