### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by justenwalker** [jippi/hashi-ui#300]
Hashi-UI panics frequently due to sending on closed channels. This is not unique to a specific set of actions, but eventually happens probably due to a race condition between sends on a channel and the shutdown process.

An example of such a panic below:
```
panic: send on closed channel

goroutine 17140 [running]:
github.com/jippi/hashi-ui/backend/nomad.(*Connection).watchGenericBroadcast(0xc421242360, 0xab05ae, 0x13, 0xab8a18, 0x20, 0xda2a60, 0xc42024c1c0, 0x975680, 0xc4214ab2f0)
        /go/src/github.com/jippi/hashi-ui/backend/nomad/connection.go:882 +0x3fc
created by github.com/jippi/hashi-ui/backend/nomad.(*Connection).process
        /go/src/github.com/jippi/hashi-ui/backend/nomad/connection.go:201 +0x38cb
```

**Comment by jippi** [comment]
Is it always in this place it crashes? are you navigating around extremely fast? line 882 is sending the initial payload for jobs page when you display the page the first time, i got no idea how the socket would go away there

**Comment by justenwalker** [comment]
@jippi I compiled from source using commit ID d5dd90c6563452470ebf618d8c64a65b2dcbc72a

**Comment by jippi** [comment]
Can you please try the builds from dockerhub or the release tab? :)

**Comment by justenwalker** [comment]
I did, still get the panic

**Comment by cross311** [comment]
@justenwalker is this similar to #263.  I never was able to get more info maybe you can get something else from our cluster.
