### ISSUE TITLE
There a way to disable the filesystem feature or a way to block certain files from being viewable?

### ISSUE THREAD

**Issue by sholland** [jippi/hashi-ui#303]
There an way to disable the filesystem feature or a way to block certain files/patterns from being viewable?

Even if I run hashi-ui-linux-amd64 with ---nomad-hide-env-data, I can still see variables which have passwords  set ( see attached )

<img width="988" alt="screen shot 2017-08-28 at 4 40 49 pm" src="https://user-images.githubusercontent.com/1458713/29798092-b1273c7a-8c0f-11e7-8786-d73d4d912c29.png">

This is running hashi-ui version 0.16.0.

**Comment by diptanu** [comment]
@jippi Yo, any help with this will be very appreciated!

**Comment by diptanu** [comment]
@sholland Well, that text you pasted is from the file system, not env var of the process. I think these are two different things that needs to be blocked - a. Env Vars, b. File system.

I would also want a flag for hiding job files since in a multi-tenant environment I don't want users to see each other's job files.

**Comment by lfarnell** [comment]
@sholland I can see your confusion here. The  --nomad-hide-env-data flag disables whether or not the Nomad env{} block values should be hidden, not environment variables. Currently there is no whitelist/blacklist or ACL's for either env vars or anything on the file system.

@diptanu Yeah, currently it doesn't look like this exists. I think this is something we should have.

**Comment by jippi** [comment]
If there is files there shouldn't be viewable in the files tab, those should be stored in /secret directory, that is by default blocked from any api access, and the recommended way to store secrets and other sensitive stuff?

**Comment by lfarnell** [comment]
Having a look at the ACL branch on the nomad repo, I believe that will probably solve the issues @diptanu is having.

**Comment by diptanu** [comment]
@jippi I agree but looks like a lot of containers "on the internet" or vendors like putting secrets rendered on the root fs of containers since other cluster schedulers don't have a secret dir. Is it too hard to add a flag for to disable `nomad fs` in hashi-ui?

**Comment by jippi** [comment]
@diptanu its not hard no, disabling it entirely is simple - filtering paths are less simple though :)

**Comment by jippi** [comment]
@sholland did you decide not to have this feature? - I'm going to close the issue, feel free to re-open
