### ISSUE TITLE
Cannot see the Task State History of the Job allocation

### ISSUE THREAD

**Issue by prathameshbhope** [jippi/hashi-ui#305]
![image](https://user-images.githubusercontent.com/7515346/29882278-8bc96388-8d7a-11e7-9544-dcd4c8f1b35a.png)

**Comment by jippi** [comment]
I don't understand the bug here, please elaborate

**Comment by prathameshbhope** [comment]
In the previous version of the UI, when you clock on the allocation ID, it will take you to a page which will have two sections --> Allocation Properties and the Task State History. With the new version, the page shows only Allocation Properties. The Task state history is useful to have first hand information on the error that causes the allocation to be in the pending state.

**Comment by jippi** [comment]
Can you please check your Console for any javascript errors? What you've sent a screenshot of is in fact the state history?

**Comment by jippi** [comment]
Do you use v0.17.0 ?

**Comment by prathameshbhope** [comment]
Yes, we use 0.17.0. We upgraded to the new version and saw couple of issues (already reported by my team mate Justen Walker). So we reverted back to 0.17.0. The picture which I sent I my comment is the task history example from the 0.17.0 version

**Comment by jippi** [comment]
Think you got some version mismatch in your previous comment? :) 

I need some JS error or reproducible steps to be able to debug & fix this

**Comment by prathameshbhope** [comment]
My bad. Yes, the 0.17.0 is the version in which we saw the issues. Right now we are running older version. I'll make sure to grab the errors or more information when we change back to new and see the same issue.

**Comment by jippi** [comment]
Looks like the issue stalled, please re-open if still relevant
