### ISSUE TITLE
add hashi-ui build/version info to the UI

### ISSUE THREAD

**Issue by goedelsoup** [jippi/hashi-ui#306]
It'd be nice to have a quick reference for the build version and possibly other info about the current build available directly through the interface.

Proposed as reference and will definitely try to throw some of our resources at it.

**Comment by discobean** [comment]
Viewing the container information without digging into the json would be great

**Comment by jippi** [comment]
Build info is that hashi-ui build info?

**Comment by jippi** [comment]
this is now present in the left nav at the bottom of the page
