### ISSUE TITLE
Nomad fs with TLS

### ISSUE THREAD

**Issue by mlosiewicz-pl** [jippi/hashi-ui#308]
I have a Nomad cluster configured with TLS with certificates for client.eu-west-1.nomad and server.eu-west-1.nomad and with configuration via environment variables I was able to run Hashi UI on the cluster. Everything works but for logs and files for allocations. I am getting 
`13:19:15.931 connection.go:78 ▶ ERROR  [4080d319] Unable to fetch directory: Get https://{{domain_name}}:4646/v1/client/fs/ls/155bb020-fbfa-53b3-7dc1-8463564917c6?path=%2Falloc%2Flogs%2F: x509: certificate is valid for server.eu-west-1.nomad, client.eu-west-1.nomad, localhost, not client..nomad`

I was having the same issue with nomad agent but setting `NOMAD_REGION` to `eu-west-1` solved the issue with agent, as far as I know there is no way to do it in Hashi UI.

**Comment by jippi** [comment]
It is 99,999% a Nomad upstream issue - sounds a lot like https://github.com/hashicorp/nomad/pull/3127

**Comment by jippi** [comment]
Oops, closed to fast! when 0.6.3 is out and hashi-ui is build against it, lets see if it works or not :)

**Comment by SoMuchToGrok** [comment]
Currently have Nomad 0.6.3 along with hashi-ui 0.18.0, everything is working great 👍

**Comment by jippi** [comment]
Thanks!
