### ISSUE TITLE
vault gui

### ISSUE THREAD

**Issue by joeblew99** [jippi/hashi-ui#316]
there is a fantastic vault GUI written BTW. I saw you mentioned that you wanted to add it on the main readme.

https://github.com/djenriquez/vault-ui

I also uses React :)
It uses the Material-UI for its style

https://github.com/djenriquez/vault-ui/blob/master/package.json

**Comment by jippi** [comment]
@joeblew99 yeah, would love to integrate Vault into the hashi-ui binary, not sure if another upstream project would want to merge with me though :)

**Comment by joeblew99** [comment]
how come you closed this ?

**Comment by jippi** [comment]
I'm not sure what the question was - my goal is to include Vault UI directly into hashi-ui at some point. :)
