### ISSUE TITLE
Consul Datacenter Not Showing Up 

### ISSUE THREAD

**Issue by tarpanpathak** [jippi/hashi-ui#322]
I'm running the Nomad and Consul (hashi-ui) service using a Nomad deploy file. The Nomad UI loads successfully but the Consul UI does not. It asks me to "Please select a consul datacenter" but don't see any options. I am attaching a screenshot that outlines the issue. Let me know if any further information is required to debug this.

### Hashi-UI Version 
v0.19.0 

<img width="1433" alt="hashi-ui-error" src="https://user-images.githubusercontent.com/10820937/30768681-35d9936e-9fc0-11e7-9bac-ba24beb67ed1.png">

**Comment by jippi** [comment]
Fixed a long time ago :D
