### ISSUE TITLE
select color scheme as parameter to distinguish environments

### ISSUE THREAD

**Issue by reinoud** [jippi/hashi-ui#326]
We run 3 different environments (prod, QA, test). All environments are configured almost identical. So the difference between them is just a few characters in a long url.

Would it be possible to select a different color scheme CSS with an environment variable, so the different instances would be visually different from a distance?

**Comment by jippi** [comment]
Having a optional ENV setting to set `CONSUL_COLOR` and `NOMAD_COLOR` that would override the [`CONSUL_COLOR`](https://github.com/jippi/hashi-ui/blob/master/frontend/src/components/ConsulTopbar/ConsulTopbar.js#L68) and [`NOMAD_COLOR`](https://github.com/jippi/hashi-ui/blob/master/frontend/src/components/NomadTopbar/NomadTopbar.js#L71) by exposing them in [config.js](https://github.com/jippi/hashi-ui/blob/master/backend/main.go#L118) handler might work
