### ISSUE TITLE
Running hashi-ui behind the fabio load balancer

### ISSUE THREAD

**Issue by pvandervelde** [jippi/hashi-ui#329]
While trying to run hashi-ui behind the [fabio load balancer](https://github.com/fabiolb/fabio).

The command line for hashi-ui is:

	--proxy-address /dashboards/hashiui/ --consul-enable --consul-address 127.0.0.1:8510 --nomad-enable --nomad-address http://172.17.35.6:4646

And my consul configuration for hashi-ui (with the fabio tags) is:

	{
		"service": 
		{
			"checks":[
				{
					"http": "http://localhost:3000",
					"id": "hashiui_health",
					"interval": "15s",
					"name": "Ping",
					"timeout": "5s"
				}
			],
			"id": "hashiui_aktfsmon01",
			"name": "hub",
			"port": 3000,
			"tags": 
			[
				"dashboard",
				"edgeproxyprefix-/dashboards/hashiui strip=/dashboards/hashiui"
			]
		}
	}

I see a page but it's the error page which looks like this:

![image](https://user-images.githubusercontent.com/96201/30793075-d154baaa-a21b-11e7-8878-b52439eff400.png)

And the error message in the console is:

	Unhandled promise rejection Exception { message: "", result: 2153644038, name: "", filename: "http://devinfrastructure.vista.co/d…", lineNumber: 1, columnNumber: 0, data: null, stack: "connectTo@http://devinfrastructure.…" }  main.f5b9c3b919e18302320c.js:1:1381689
		P/</t< http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:1381689
		e.exports http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:520775
		P/< http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:1381566
		e.exports http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:197437
		<anonymous> http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:284480
		y http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:284338
		b http://devinfrastructure.vista.co/dashboards/hashiui/nomad/static/main.f5b9c3b919e18302320c.js:1:284358

It looks like this is a WebSocket issue but I'm not entirely sure what other settings I should enable where. Fabio should handle [web sockets](https://github.com/fabiolb/fabio/wiki/Websockets) automatically as far as I can tell. 

All other sites (grafana, kibana, jenkins) that I'm routing through Fabio work just fine, but then I don't think any of them use websockets (although I haven't checked)

Does anybody have any idea on what switches / settings / configurations / magic I can try to make this work?

**Comment by pvandervelde** [comment]
I just grabbed the latest release and I still can't get this to work. I'm pretty sure the error is on my end. I've tried the following things:

* Run HashiUI standalone, i.e. talk to it on http://myhost:3000. This works fine
* Run HashiUI behind fabio, by setting the proxy-address on the command line to: `http//myproxy/dashboards/hashiui/` and letting fabio strip the `/dashboards/hashiui` section
* Run HashiUI behind fabio, by setting the proxy-address on the command line to: `http//myproxy/dashboards/hashiui/` and not letting fabio strip anything
* Run HashiUI behind fabio, by setting the proxy-address on the command line to `/dashboards/hashiui/`

Is there any documentation / source code that I can look at to help me figure out what the correct configuration is?

**Comment by jippi** [comment]
https://github.com/jippi/hashi-ui/tree/master/scripts has both nginx and fabio example i've used a loooong time ago (tested nginx rewrite a few days ago)

**Comment by pvandervelde** [comment]
I can't see the fabio one but I do see a traefik one. From that it looks like I need to set up fabio to redirect to `/dashboards/hashiui` and strip that path too (i.e. strip `/dashboards/hashiui`). And then set hashi-ui to run with the `--proxy-address` setting to `/dashboards/hashiui`

**Comment by jippi** [comment]
not afaik no, should just work (tm) try and ask in the gitter room for hashi-ui or gitter for nomad, I'm sure someone must have set it up at some point :)

**Comment by pvandervelde** [comment]
Will do. Thanks

**Comment by pvandervelde** [comment]
Ok so an update on this. One with the latest version of [fabio (1.5.3)](https://github.com/fabiolb/fabio/releases/tag/v1.5.3) the whole proxy thing mostly work. One minor issue I've noticed is  that the links to the nomad and consul pages in the side bar refer to the unproxied addresses, i.e. if the proxy address is set to `/myproxy` then the side bar links go to `http://myproxyhost/nomad` and `http://myproxyhost/consul` instead of `http://myproxyhost/myproxy/nomad` and `http://myproxyhost/myproxy/consul` respectively.
