### ISSUE TITLE
HashiUI hang on firefox

### ISSUE THREAD

**Issue by pvandervelde** [jippi/hashi-ui#348]
Running HashiUI 0.20.1hangs firefox. The command line is:

    hashi-ui-windows-amd64.exe -consul-enable -consul-read-only -nomad-enable -nomad-address http://192.168.3.25:4646 -nomad-read-only

The output on the console is:

    [36mINFO[0m[0000] -----------------------------------------------------------------------------
    [36mINFO[0m[0000] |                             HASHI UI                                      |
    [36mINFO[0m[0000] -----------------------------------------------------------------------------
    [36mINFO[0m[0000] | listen-address       : http://0.0.0.0:3000                                |
    [36mINFO[0m[0000] | server-certificate   :                                                    |
    [36mINFO[0m[0000] | server-key          :                                                    |
    [36mINFO[0m[0000] | proxy-address       :                                                    |
    [36mINFO[0m[0000] | log-level           : info                                               |
    [36mINFO[0m[0000] | nomad-enable        : true                                               |
    [36mINFO[0m[0000] | nomad-read-only      : Yes                                                |
    [36mINFO[0m[0000] | nomad-address        : http://192.168.3.25:4646                           |
    [36mINFO[0m[0000] | nomad-ca-cert        :                                                    |
    [36mINFO[0m[0000] | nomad-client-cert    :                                                    |
    [36mINFO[0m[0000] | nomad-client-key     :                                                    |
    [36mINFO[0m[0000] | nomad-skip-verify    : false                                              |
    [36mINFO[0m[0000] | nomad-hide-env-data  : false                                              |
    [36mINFO[0m[0000] | nomad-skip-verify    : No                                                 |
    [36mINFO[0m[0000] | consul-enable               : true                                               |
    [36mINFO[0m[0000] | consul-read-only     : Yes                                                |
    [36mINFO[0m[0000] | consul-address       : 127.0.0.1:8500                                     |
    [36mINFO[0m[0000] | consul.acl-token     :                                                    |
    [36mINFO[0m[0000] -----------------------------------------------------------------------------
    [36mINFO[0m[0000]
    [36mINFO[0m[0000] Listening ...
    [31mERRO[0m[0006] No region provided                            [31mconnection_id[0m=2f89e0cc
    [31mERRO[0m[0012] No region provided                            [31mconnection_id[0m=1b76816f
    [36mINFO[0m[0013] Started watching /jobs/list                   [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0013] Started watching /nodes/list                  [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0013] Started streaming /members/list               [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0013] Started streaming /cluster/stats              [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0013] Started watching /allocations/list            [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0023] WaitGroups: 6 | Subscriptions: /members/list, /cluster/stats, /allocations/list, /internal/keep-alive, /jobs/list, /nodes/list  [36mconnection_id[0m=50dc523d
    [36mINFO[0m[0033] WaitGroups: 6 | Subscriptions: /internal/keep-alive, /jobs/list, /nodes/list, /members/list, /cluster/stats, /allocations/list  [36mconnection_id[0m=50dc523d

0.18 and 0.19 seem to work just fine.

**Comment by jippi** [comment]
Can you try master ?  thats `jippi/hashi-ui:latest`

**Comment by pvandervelde** [comment]
Is there a windows build for that somewhere? I just quickly tried building it and there was lots of complaining. I don't have time at the moment to set up a complete build environment (it's 10pm on friday here)

**Comment by jippi** [comment]
does it only freeze up in firefox?  is it on all pages it freezes up? what about chrome or IE?

**Comment by pvandervelde** [comment]
Ok so more info. It might be related to the state of nomad. I now have a nomad server and agent running and it works fine in all three browsers (using a lot of CPU though). Earlier on I only had a nomad host. I shall do some more testing to see what gives

**Comment by pvandervelde** [comment]
The following state should reproduce it:

* Consul 0.9.3 running on the local machine as a server
* Nomad 0.6.3 running on the local machine as server, connecting to the local consul
* HashiUI 0.20.1 running on the local machine connecting to the local consul and the local nomad.

1. Start consul. Wait for it to acquire leadership
2. Start nomad. Wait for it to start writing output to the console
3. Start hashiui
4. Load the hashiui page for nomad on http://localhost:3000/nomad

This works for about 15 odd seconds and then nomad goes mental. The output from nomad looks like:

    2017/09/29 22:13:55.713911 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.713911 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.713911 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.714912 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.714912 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.714912 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.714912 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.715911 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.715911 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.715911 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.717910 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.717910 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.718911 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (1.0004ms)
    2017/09/29 22:13:55.718911 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.718911 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.718911 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.719910 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.719910 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (0s)
    2017/09/29 22:13:55.719910 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.719910 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.720910 [DEBUG] http: Request /v1/nodes?region=calvinverse&stale=&wait=10000ms (1.0004ms)
    2017/09/29 22:13:55.720910 [DEBUG] http: Request /v1/jobs?region=calvinverse&stale=&wait=120000ms (0s)
    2017/09/29 22:13:55.721911 [DEBUG] http: Request /v1/allocations?region=calvinverse&stale=&wait=120000ms (1.0004ms)

And scrollling rappidly on the console, i.e. there's a lot of requests going to Nomad. The hang in firefox seems to be due to the fact that firefox can't seem to handle the updates. The machine is running at near 100% CPU with all the updates in Nomad. 

By the way it also kills the Chrome window, Chrome just takes longer

**Comment by jippi** [comment]
is the cluster entirely empty?

**Comment by pvandervelde** [comment]
Assuming you mean no nomad non-server agents, then yes. But if I have a single nomad non-server agent running (in addition to the server) the same happens. Lots of nomad log entries which I assume are due to hashiui hitting a nomad api endpoint.

I haven't tested with any running jobs yet. I'm in the process of setting up some test docker containers but haven't managed to get there yet.

**Comment by jippi** [comment]
Fixed in master, probably a Nomad SDK bug - if you add *any* job to the cluster it should fix the issue until an actual release has been created with the bugfix

**Comment by pvandervelde** [comment]
Awesome! I shall remember that.
