### ISSUE TITLE
Show job name and not id in jobs table

### ISSUE THREAD

**Issue by rejeep** [jippi/hashi-ui#352]
Hi,

First of all, thanks for Hashi-ui, it's great!

I noticed that the jobs table show the job id, even though it says name in the title. I think it would make more sense to show name or both. In our case the ID is just a random number and says nothing.

What do you think?

**Comment by jippi** [comment]
Seems legit, there are cases where only the Job ID is available in the Nomad replies, so can't easily do it cross all parts of the UI

**Comment by rejeep** [comment]
So then we can either try with name if that exist, otherwise use the id. Or we can have two columns, one for each.

**Comment by jippi** [comment]
i would just use name where possible :)

**Comment by rejeep** [comment]
Then I think we should also change the "Job" property on the allocation page to do the same.

**Comment by jippi** [comment]
all the changes would be 100% JavaScript (react) if you want to give it a try :)

**Comment by rejeep** [comment]
Thats better for sure, have no experience with react though. I would be happy to implement it myself, I just have hard to find time. We’ll see what happens. 🙂
