### ISSUE TITLE
'Consul Health integration' doesn't show health in multi-datacenter scenarios

### ISSUE THREAD

**Issue by jolexa** [jippi/hashi-ui#353]
In our setup, the hashi-ui configuration has the consul address set to the local dc. This means that if you have applications running in another datacenter with nomad, the health feature doesn't show the status properly.

My question is, is is possible for hashi-ui to show the consul health status for an application running in a different datacenter than the ui? Do we need to configure the consul address differently?

**Comment by jippi** [comment]
I was lazy when i did the initial setup, so I just used local DC everywhere, but to fix it I need to lookup the Nomad Client's `Attributes.consul.datacenter` prior talking to Consul and then include that in the Consul query :)

**Comment by jippi** [comment]
that was easier than expect if this work, should be in master build in a few minutes
