### ISSUE TITLE
Not able to enable read only for both nomad and consul using hashi-ui

### ISSUE THREAD

**Issue by pravinkumarb84** [jippi/hashi-ui#359]
I am trying to enable read only mode for both nomad and consul using hashi-ui using below commands.

--nomad-enable --consul-enable --nomad-read-only true --consul-read-only true

But it enables read only for nomad alone on startup

**Comment by jippi** [comment]
can you try the ENV variable version?

**Comment by jippi** [comment]
stalled and can't reproduce
