### ISSUE TITLE
Client Stats seem to include the CPU and RAM allocations of failed allocations

### ISSUE THREAD

**Issue by marcjay** [jippi/hashi-ui#361]
The Client Stats graphs seem to be including the resources required by failed allocations in the total Allocated value.

![image](https://user-images.githubusercontent.com/580744/32494577-14f8cc5a-c3ba-11e7-9c0d-5d8e77118db5.png)

My guess is when the check is made here: https://github.com/jippi/hashi-ui/blob/v0.22.0/backend/nomad/nodes/stats.go#L77 to exclude allocations for which the DesiredStatus is not "run", it should also check that the ClientStatus is "running" and skip if not.

This is the Allocation info for one of the allocations that failed (due to a driver error)

![image](https://user-images.githubusercontent.com/580744/32494683-7c5017be-c3ba-11e7-9e18-84e490bb5085.png)

Will happily submit a PR for the fix, but it seems too small to be of worth

**Comment by jippi** [comment]
oh yeah, that seem legit !

**Comment by hsmade** [comment]
Thanks!

**Comment by marcjay** [comment]
Thanks for the merge!
