### ISSUE TITLE
Sidebar links to main nomad and consul pages point to wrong address in case a proxy is active

### ISSUE THREAD

**Issue by pvandervelde** [jippi/hashi-ui#363]
With the latest version of fabio (1.5.3) the whole proxy thing mostly work. One minor issue I've noticed is that the links to the nomad and consul pages in the side bar refer to the unproxied addresses, i.e. if the proxy address is set to /myproxy then the side bar links go to http://myproxyhost/nomad and http://myproxyhost/consul instead of http://myproxyhost/myproxy/nomad and http://myproxyhost/myproxy/consul respectively.

**Comment by jippi** [comment]
should be fixed now in latest/master

**Comment by pvandervelde** [comment]
@jippi Any idea when a new release with these changes will be available? I don't see a specific commit on master that would fix this so I assume it's one of the earlier ones / a combination of earlier ones.
