### ISSUE TITLE
Failing behind proxy

### ISSUE THREAD

**Issue by perrymanuk** [jippi/hashi-ui#369]
When I load http://x.x.x.x:3000/nomad the content is failing to load that will normally show the regions, however if I add a trailing slash eg http://x.x.x.x:3000/nomad/ the content will load normally.

**Comment by jippi** [comment]
using master or latest tag?

**Comment by perrymanuk** [comment]
using the latest image from dockerhub

**Comment by perrymanuk** [comment]
using the latest docker image I have the error however with the v0.22.0 tag it works perfectly

**Comment by perrymanuk** [comment]
thanks! :-D
