### ISSUE TITLE
Support registering hashi-ui as a consul service

### ISSUE THREAD

**Issue by lord2800** [jippi/hashi-ui#373]
I'd love to have hashi-ui register itself with Consul as a service. Ideally, I'd love to be able to specify tags as well, so I can set it up with [Fabio](https://github.com/fabiolb/fabio) automatically. I can look and try to submit a PR if you'd prefer that--Go is not my strong suit, though.

**Comment by hsmade** [comment]
Easiest way to do that is creating a nomad job for hashi-ui

**Comment by jippi** [comment]
As @hsmade said, simply adding a `service{}` stanza in the hashi-ui job should do the trick :)

**Comment by lord2800** [comment]
Hmm. I'll see if I can finagle something so it can still talk to consul and nomad within a nomad job. I have everything listening on localhost with no permission outside of that for security reasons.
