### ISSUE TITLE
Consul status not showing

### ISSUE THREAD

**Issue by rafaelpirolla** [jippi/hashi-ui#374]
As of nomad 0.7.1:
https://github.com/hashicorp/nomad/blob/v0.7.1/CHANGELOG.md

BACKWARDS INCOMPATIBILITIES:
client: The format of service IDs in Consul has changed. If you rely upon Nomad's service IDs (not service names; those are stable), you will need to update your code. [GH-3632]

I believe it's the case for the consul checks, right?

**Comment by jippi** [comment]
thats possible, if they no longer include the allocation id, then it will break - I'm not in 0.7.1 yet, so can't test :) 

hopefully next week

**Comment by jippi** [comment]
Fixed in master
