### ISSUE TITLE
Support for nomad acl tokens

### ISSUE THREAD

**Issue by adragoset** [jippi/hashi-ui#376]
Dunno if this is in or not but I didn't see a setting for a nomad acl token in the configuration parameters for nomad. RIght now im having to run the anonymous token with all access permissions.

**Comment by jippi** [comment]
you mean a UI where you can put in a custom token?

**Comment by k1ng87** [comment]
yep yep! +1 on this...I see consul token but not nomad token.....we just implemented ACL tokens in nomad and now hashi-ui doesn't work anymore cause it doesn't have access since it doesn't have a spot for nomad tokens

**Comment by adragoset** [comment]
@jippi A configuration parameter to set a nomad acl token for the nomad ui like the consul ui's CONSUL_HTTP_TOKEN environment setting.

**Comment by SelwynL** [comment]
+1 would really like to see nomad token support

**Comment by mirasrael** [comment]
Hi @jippi When do you plan to release next version with Nomad ACL support? (we also need this for our infrastructure)

**Comment by jippi** [comment]
"now" I guess - https://github.com/jippi/hashi-ui/releases/tag/v0.24.0 :)
