### ISSUE TITLE
Vault UI Design Doc

### ISSUE THREAD

**Issue by Wintermute1** [jippi/hashi-ui#383]
Hi,

Has any progress been made with adding Vault integration?

I would love to contribute on this as it's daily use case would make life easier for doing tedious tasks.

Would it be possible to get a list of requirements or a very general roadmap?

Thanks

**Comment by jippi** [comment]
No progress has been made.

It would probably be usage driven like everything else, so no requirements tbh :) 

Implement the basic stuff and expand from there

**Comment by jippi** [comment]
not going to do vault now that Vault OSS got native ui
