### ISSUE TITLE
Nomad 0.8.1 compatibility: Adjust to change in semantics of node-drain

### ISSUE THREAD

**Issue by ramSeraph** [jippi/hashi-ui#389]
the new version of nomad has changed semantics for node draining.. introduces the concept of scheduling eligibility.. also the concept of a node drain deadline and more fine grained controls on draining in general. 

This issue is a placeholder for discussion regarding changes required in hashi-ui for the same

**Comment by dukeland9** [comment]
+1 for this issue.

**Comment by jippi** [comment]
i've still not upgraded to 0.8.x myself - will happen within the next month or so, so expect an update in hashi-ui (if no one does it before me) within 1-2 months :)

**Comment by jippi** [comment]
fixed in #404
