### ISSUE TITLE
Sometimes Events for TaskState is null which leads to Hashi UI whole web interface fail

### ISSUE THREAD

**Issue by mirasrael** [jippi/hashi-ui#396]
![image](https://user-images.githubusercontent.com/475445/40107315-97f1c432-5900-11e8-9fb7-4664286dfee8.png)

Unfortunately I can't provide stack trace and corresponding JSON, because while debugging for some reason it just start working. But it looks like "can't call reverse on null object" which means for some reason TaskState in received JSON doesn't contain "Events" collection (in the same time it has a lot of correct task states with set "Events" key).

**Comment by jippi** [comment]
fixed in #404
