### ISSUE TITLE
Log files does not show up in UI under Allocations > Logs

### ISSUE THREAD

**Issue by manjunath-br** [jippi/hashi-ui#398]
The log files does not list out or show in the UI under Jobs > job1 > Allocations > job1 > Logs. I manual verified that the logs exists in the /alloc path.

The UI is listening on the port 80 and firewall has necessary port opened for the UI.

The logs does not provide much information. However, I do see the following entries:
```
time="2018-05-23T03:35:43Z" level=error msg="Could not read payload: websocket: close 1006 (abnormal closure): unexpected EOF" connection_id=909c4b17 source=connection

time="2018-05-23T03:35:43Z" level=error msg="[/allocation/1be594f6-9b6d-d8e8-eb21-0280a530778e/info] Shutting down due to closed destroyCh" connection_id=909c4b17 source=connection

time="2018-05-23T03:35:43Z" level=info msg="Stopped watching /allocation/1be594f6-9b6d-d8e8-eb21-0280a530778e/info" connection_id=909c4b17 source=connection

time="2018-05-23T03:35:43Z" level=error msg="[/nodes/list] Shutting down due to closed destroyCh" connection_id=909c4b17 source=connection

time="2018-05-23T03:35:43Z" level=info msg="Stopped watching /nodes/list" connection_id=909c4b17 source=connection

time="2018-05-23T03:35:47Z" level=error msg="No longer subscribed to /allocation/1be594f6-9b6d-d8e8-eb21-0280a530778e/info" connection_id=909c4b17 source=connection

```

**Comment by molin0000** [comment]
Do you click on the stdout or errout button in the UI page?

**Comment by manjunath-br** [comment]
@molin0000 I am not sure what button you are referring. 

Screenshot of my UI which is run v0.25.0. As you can see there are no log files listed. However, in the nodes I can see the log files are available. 

<img width="1231" alt="screen shot 2018-05-23 at 1 13 55 pm" src="https://user-images.githubusercontent.com/27811548/40410413-64b58b86-5e8b-11e8-9ae6-349c8c342cc7.png">

**Comment by jippi** [comment]
what version of nomad do you use? I haven't tested hashi-ui on 0.8.x yet - and it include some changes to the fs layer

**Comment by manjunath-br** [comment]
@jippi  I am using the 0.8.0 version of nomad.

**Comment by jippi** [comment]
Can you try with 0.8.3 ? bee a few fixed around issues like that

**Comment by manjunath-br** [comment]
I will try with 0.8.3 version and get back with the outcome.

**Comment by jippi** [comment]
also please provide nomad server/client logs - should be some errors there as well

**Comment by manjunath-br** [comment]
I tried with the new nomad version 0.8.3 but the issue still remains. I have attached the logs for server/client and UI.

PS: I spinned up three new servers with latest version of nomad and made them join the server cluster with old version. Removed the old servers from cluster. Spinned up new clients with latest version of nomad. 

[nomadserver.log](https://github.com/jippi/hashi-ui/files/2031422/nomadserver.log)
[client.log](https://github.com/jippi/hashi-ui/files/2031420/client.log)
[hashiUI.log](https://github.com/jippi/hashi-ui/files/2031421/hashiUI.log)

**Comment by manjunath-br** [comment]
@jippi I tweaked the firewall rules and the logs started showing back in the UI after the upgrade. The issue is resolved.
