### ISSUE TITLE
Consistent task event ordering

### ISSUE THREAD

**Issue by iverberk** [jippi/hashi-ui#4]
Right now the task events are not displayed chronologically. This is confusing and should be ordered with the latest task events at the top.

**Comment by EcofitBrendan** [comment]
@iverberk I'd be happy to give adding this functionality a shot, seems like a good way to introduce myself to the code.

**Comment by iverberk** [comment]
Excellent! Let me know if you have any questions. The idea was to always show the latest ten task events on the cluster page.

**Comment by EcofitBrendan** [comment]
It'll likely be a slow start for me, I've never done any significant work with React before, but if I have any questions I'll be in touch.

**Comment by iverberk** [comment]
Hi @EcofitBrendan, were you able to make some progress on this? If you need help just let me know.

**Comment by EcofitBrendan** [comment]
No, unfortunately I've been relatively swamped for the last two weeks. It's still on my radar but I doubt I will get a chance to look at it until this weekend.

**Comment by jippi** [comment]
any progress on this one @iverberk ? :)

**Comment by jippi** [comment]
i haven't noticed any out-of-order issues for a while - i guess either nomad or we fixed this? :)
