### ISSUE TITLE
Javascript error v0.25.0 against Nomad 0.8.4

### ISSUE THREAD

**Issue by jamesdmorgan** [jippi/hashi-ui#402]
Hi,

Just upgraded our Nomad cluster to 0.8.4 and hit a javascript bug when loading the Hashi UI.

It initially loads then I get a blank page

```
TypeError: Cannot read property 'reverse' of null
    at ClusterEvents.js:25
    at Array.forEach (<anonymous>)
    at ClusterEvents.js:24
    at Array.forEach (<anonymous>)
    at t.value (ClusterEvents.js:22)
    at u (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at r (react-dom.production.min.js:161)
    at i (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:162)
u @ react-dom.production.min.js:164
```

Has anybody seen this before? 

Cheers

James

**Comment by jippi** [comment]
might be same as https://github.com/jippi/hashi-ui/issues/396 ?

**Comment by jamesdmorgan** [comment]
Hey @jippi yeah could well be. Just realised that I can't downgrade our cluster to 0.7.3 from 0.8.4. Panics on startup. Do you know if there will be a fix soon? Appreciate the speedy response

**Comment by jamesdmorgan** [comment]
Update - I was only getting the problem on the cluster / home page. If I navigate to jobs etc it is fine. Now when I navigate to the cluster page it loads ok. Similar behaviour in #396

**Comment by jippi** [comment]
i hope the next week will feature me upgrading to 0.8.x at $work - by then i can sneak in time to fix up hashi-ui :)

**Comment by jamesdmorgan** [comment]
Amazing thanks.
