### ISSUE TITLE
nomad 0.8.4 job rolling restart fails in the absence of update stanza in job definition

### ISSUE THREAD

**Issue by ramSeraph** [jippi/hashi-ui#403]
seems like a regression of #302 and hashicorp/nomad #3132

**Comment by ramSeraph** [comment]
might just be an issue with usage of older client library with the numbered hashiui release.. will try to build with updated client libraries in master and update here

**Comment by jippi** [comment]
it's very likely that using 0.7 SDK (currently hashi-ui) against 0.8 might produce some interesting side-effects 

also tracked in #389

**Comment by jippi** [comment]
similar the `migrate` stanza isn't supported either atm
