### ISSUE TITLE
Allocations returns 500 error with nomad v0.7.1 and hashi-ui v0.26

### ISSUE THREAD

**Issue by ionosphere80** [jippi/hashi-ui#405]
All of my nomad nodes run v0.7.1. After upgrading to hashi-ui v0.26, looking at allocations returns a 500 error saying the node isn't running a nomad client. Interestingly, this only seems to impact stats. Reverting to hashi-ui v0.25 resolves the issue.

**Comment by jippi** [comment]
hashi-ui v0.26 will be nomad 0.8+ only going forward

a lot of internal changes makes it really hard to support both
