### ISSUE TITLE
Can't find nomad and consul.

### ISSUE THREAD

**Issue by jarrettj** [jippi/hashi-ui#419]
Hi,

Good day.

I used the following docker command:
```
$ docker run -e NOMAD_ENABLE=1 -e NOMAD_ADDR=http://localhost:4646 -e CONSUL_ENABLE=1 -e CONSUL_ADDR=http://localhost:8500 -p 8000:3000 jippi/hashi-ui
```
Output:
```
time="2018-10-25T06:34:26Z" level=fatal msg="Unable to communicate with Nomad: Get http://localhost:4646/v1/status/leader?wait=60000ms: dial tcp 127.0.0.1:4646: getsockopt: connection refused"
```

I have nomad and consul running directly on my machine (MacOS). Both are accessible on via my browser at localhost. Any ideas? Thanks.

Regards.
JJ

**Comment by pauloconnor** [comment]
You need to use the real IP of your laptop. Localhost in this instance refers to the docker container that hashi-ui is running in.

**Comment by jippi** [comment]
@pauloconnor is right, closing up
