### ISSUE TITLE
NOMAD_PORT_http can collide with NOMAD_PORT_{port_label} env variables supplied by nomad

### ISSUE THREAD

**Issue by adragoset** [jippi/hashi-ui#431]
If you deploy hashi ui through nomad using dynamic ports and your port label is defined as http it will collide with the env variable NOMAD_PORT_http and set hashiui to use a non default port thats dynamically assigned by nomad as the host port. This causes hashiui to listen on an arbitrary port in the container rather than the default port. My suggestion is to rename the env variable hashiui uses to NOMAD_LISTEN_PORT_http so it cannot collide with env variables supplied by nomad.

**Comment by jippi** [comment]
That is considered a feature :) 

If it collides with other ports, I would recommend renaming your other port
