### ISSUE TITLE
support for spread stanza

### ISSUE THREAD

**Issue by jcomeaux** [jippi/hashi-ui#436]
Looks like hashi-ui doesn't support the new "spread" stanza.  I submit a job directly to the nomad api via json POST and I can see the "Spreads" stanzas show up in the Nomad ui, but not in hashi-ui.  Also, whenever I change the task counts via hashi-ui, the job is overwritten and the "Spreads" configuration gets zeroed out.

**Comment by jippi** [comment]
Correct, we need to bump the Nomad SDK to 0.9.x instead of 0.8.x :)

**Comment by skyrocknroll** [comment]
@jippi is there already plan to support nomad 0.9.x  and what would be the timeline?

**Comment by jippi** [comment]
Fixed in https://github.com/jippi/hashi-ui/releases/tag/v1.1.0
