### ISSUE TITLE
GUI bug and unknown allocation id

### ISSUE THREAD

**Issue by mnuic** [jippi/hashi-ui#439]
Hi,

Today we deployed last version 1.1.0 and after that we are seeing a lot of errors like this in browser:
```
Unexpected response code: 500 (unknown allocation ID “XXXXXXX”)
```

also this:
![Screenshot 2019-06-14 at 09 39 23](https://user-images.githubusercontent.com/17595622/59492368-1b3a9a80-8e89-11e9-963d-a80ad54e634c.png)

Consul version: 1.5.0
Nomad version: 0.8 and 0.9.1

Log:
```
level=error msg="connection: unable to stream /allocation/43e782e3-43b9-56de-2191-0f994917c105/stats?simple=true&interval=3s: Unexpected response code: 500 (unknown allocation ID \"43e782e3-43b9-56de-2191-0f994917c105\")" connection_id=afb69d42 source=connection
level=error msg="connection: unable to stream /allocation/c60bdbfe-ff11-96fa-e9d7-52e4ac43c965/stats?simple=true&interval=3s: Unexpected response code: 500 (unknown allocation ID \"c60bdbfe-ff11-96fa-e9d7-52e4ac43c965\")" connection_id=afb69d42 source=connection

```

**Comment by jippi** [comment]
`Unexpected response code: 500` sounds like a potential ACL issue?

**Comment by mnuic** [comment]
We don't use ACL of any sort, that's interesting part

**Comment by hsmade** [comment]
Getting the same thing here, after upgrading.

**Comment by hsmade** [comment]
It happens when I do a rolling restart. I see the new alloc coming online in hashi-ui, and then the error.
I'll try to get some more info

**Comment by hsmade** [comment]
![image](https://user-images.githubusercontent.com/1136373/59668794-66221e00-91b9-11e9-8779-cfccf769c908.png)

**Comment by hsmade** [comment]
So ALLOC_STATS is failing?
This is for existing allocs. I'm not restarting or anything, just switched to the allocs page for a service.
Nomad version is 0.9.3

**Comment by hsmade** [comment]
I can reproduce it with hash-ui-1.1.0

**Comment by hsmade** [comment]
And I can't reproduce it when using nomad-0.9.3

**Comment by mnuic** [comment]
just installed nomad 0.10.5, hashi_ui 1.3.4 and this still happens randomly. We are using haproxy but even when I hit the container IP addr and port for hashi_ui it's the same:
`Get http://NomadClientIP:4646/v1/job/ServiceName?index=1337027&namespace=default&region=DcRegion&stale=&wait=120000ms: EOF`

**Comment by mnuic** [comment]
This is starting to be pain in the ... even without the proxy, when manually connecting to hashi_ui container above error happens.

We are using Consul v1.7.2 and Nomad v0.10.5.

**Comment by mnuic** [comment]
This happens because Nomad introduced limits in 0.10.3 version, explained [here](https://github.com/jippi/hashi-ui/issues/557#issuecomment-626734995).  

So I'm closing this one.
