### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by PmcFizz** [jippi/hashi-ui#577]
ubuntu
node:12.18.0 
yarn: v1.22.4

333] ./src/main.js 2.2 KiB {0} [built] [failed] [1 error]
    + 331 hidden modules

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'concat' of undefined
    at findPath (/home/fizz/Documents/hashi-ui/frontend/node_modules/babel-plugin-recharts/lib/index.js:55:26)

![image](https://user-images.githubusercontent.com/13403284/85520983-344a5f80-b636-11ea-800b-08fa13d3b1ce.png)

**Comment by Aisuko** [comment]
I hit the same issue with the `root` folder and use the command `make` on the macOS Catalina.

**Comment by PmcFizz** [comment]
需要删除yarn.lock文件 重新安装包
