### ISSUE TITLE
Lifecyle Hook goes missing on job restart

### ISSUE THREAD

**Issue by gpaggi** [jippi/hashi-ui#662]
I'm using Nomad 1.0.4 and Hashi-ui 1.3.8 with a job which uses Connect.
```
[...]
    service {
      name = "[[.api.name]]"
      port = "http"
      tags = [
          "prometheus",
        ]
      check {
        type     = "http"
        path     = "/healthcheck"
        interval = "3s"
        timeout  = "2s"
        port = "http"
      }
      connect {
        sidecar_service {
          tags = ["connect"]
          proxy {
            config {
              envoy_prometheus_bind_addr = "0.0.0.0:9999"
              protocol = "http"
            }
          }
        }
      }
    }
[...]
```
I noticed that when triggering a rolling restart of the job via the UI the Lifecycle hook block for the Connect sidecar goes missing:
(output of inspect side by side diff, pre-restart and after restart)
```
"Lifecycle": {									"Lifecycle": null,
  "Hook": "prestart",										
  "Sidecar": true										
},												
```
Also the Consul tag on the SidecarService goes missing:
```
"Tags": [									"Tags": null
  "connect"											                                    
]												                                
```
I bumped nomad/api from `v0.0.0-20191003141308-550e1b1a1e76` to `v0.0.0-20210318193511-7c7569674c9d`, built a test version and that seems to fix the issue.

Any chances you can bump nomad/api and release a new version? :)

**Comment by jippi** [comment]
Sure, a PR would be welcome :)

**Comment by ketzacoatl** [comment]
Would this make hashi-ui not work with an older version of Nomad? Breaking support for an older nomad is ok, but it would be good to be clear about which versions of the hashi-ui work with which versions of Nomad.

**Comment by gpaggi** [comment]
Good question. Although I believe it should still work on older versions, Nomad API doesn't promise backwards compatibility and I haven't explicitly tested it.

**Comment by jippi** [comment]
It's a limitation in the Nomad Go SDK

It uses the structs present in the Nomad Go SDK version and then marshals JSON to structs and back again - so any new field(s) in a release more recent than hashi-ui uses will be silently dropped - it's a huge annoyance of mine as well :( 

The best thing is to probably try to automate updating the Nomad SDK automatically
