### ISSUE TITLE
Create jobs through UI

### ISSUE THREAD

**Issue by iverberk** [jippi/hashi-ui#7]
Show a form to create new job definitions

**Comment by carlpett** [comment]
I can see the value in this, but I would prefer if I could toggle it off (environment var for example). The ui provides great insight for all the development teams, but we don't want a separate ad-hoc deployment pipeline from it.

**Comment by iverberk** [comment]
@carlpett duly noted. I can understand that you want additional the deployments shielded.

**Comment by jippi** [comment]
I think I'm not going to do this, same for editing jobs other than raw JSON - the win isn't that big, and the complexity is quite high.
