### ISSUE TITLE
Allow job control from the UI

### ISSUE THREAD

**Issue by iverberk** [jippi/hashi-ui#8]
Introduce ways of starting and stopping jobs.

**Comment by mohitarora** [comment]
+1 for this

**Comment by johnoc2000** [comment]
+1 for this

**Comment by jippi** [comment]
some work on this is being done here https://github.com/jippi/hashi-ui/pull/128

**Comment by jippi** [comment]
Basic scale up/down/stop a task group now works in latest 

![image](https://cloud.githubusercontent.com/assets/22841/21230814/6bbab466-c2e6-11e6-879c-132ed32dc93b.png)

**Comment by jippi** [comment]
Jobs can now be updated from the UI; https://github.com/jippi/hashi-ui/releases/tag/v0.8.0

**Comment by jippi** [comment]
Jobs can now also be stopped, closing this issue as https://github.com/jippi/hashi-ui/releases/tag/v0.9.0 should finish the features requested here :)
