### ISSUE TITLE
basic filtering

### ISSUE THREAD

**Issue by jippi** [jippi/hashi-ui#93]
Being able to filter lists by "simple" means would be very powerful 

`freetext` = leftmost matching ala `nomad` would match `nomad%` (from SQL)
`enum` = dropdown
- `Members` 
  - ID = feetext 
  - Datacenter = enum
  - Name = freetext
  - Class = enum
  - Drain = enum
  - Status = enum
- `Nodes` 
  - ID = freetext
  - DC = enum
  - Name = enum
  - Class = enum
  - Drain = enum
  - Status = enum
- `Job`
  - ID = freetext
  - Type = enum
  - Priority = enum
  - Status = enum
- `Evaluations`
  - ID = freetext
  - Job = freetext (enum if rows are few)
  - Status = enum
  - Type = enum
  - Priority = enum
- `Allocations`
  - ID = freetext
  - Job = freetext (enum if rows are few)
  - Client Status = enum
  - Desired Status = enum
  - Node = freetext
  - Evaluation = freetext

_bonus_

For lists where there are a `CreatedTime` or similar time-sensitive data, it would be nice to be able to pick a date-range for the events you wish to see

**Comment by themalkolm** [comment]
I just mention here that you probably want to make a conscious decision where you do this: frontend or backend.

Frontend side is very easy to do. You can use, say, https://github.com/glittershark/reactable and in no time you will get basic sorting/filtering everywhere. We did it this way. Shiny and cool.

Backend side is a bit trickier as it will require proper sync of sort/filter states between backend and fronted but in long run it is better. Especially if ever you later implement pagination support for all lists as in this case everything *must* be done on the backend side.

My 5 cents :)

**Comment by jippi** [comment]
My personal preference is to do it client side, and fix server side once it becomes needed / required.

Right now, imo, doing it fast is better than doing it right for most of the basic features.

Once the problem domain is well understood, then we can push it to the backend :)

**Comment by themalkolm** [comment]
Sure, just saying that later it will require you to redo everything. We had this and it was annoying to throw away everything due pushing everything to be.

**Comment by iverberk** [comment]
@themalkolm did you have significant numbers that made you stray away from client side sorting/filtering? We are considering this now and I'm curious if you have any additional information on this. Thanks!

**Comment by themalkolm** [comment]
It is about the whole package: pagination, sorting and filtering.

We run several < 10 jobs and each has > 1000 processes. This made UI unresponsive due it's naive approach with sending all list elements every time.

So we still fetch all of them on backend side but send only the current page.

**Comment by iverberk** [comment]
I assume you didn't create DOM elements for all of them, so the unresponsiveness came from large message transfer and memory size?

**Comment by themalkolm** [comment]
No,

* Listing all allocations creates DOM elements for all of them (at least the version I used)
* Transferring became bottleneck as well.

Not sure what _exactly_ caused issues there but this or other way sending all elements was identified as the main suspect. So we implemented pagination and everything went back to normal.

**Comment by themalkolm** [comment]
To make matter worse we restart/update these jobs quite often. This builds up a lot of internal history in nomad i.e. completed allocations.

**Comment by iverberk** [comment]
yep, those are going to be GC'ed eventually but for sure they stick around for a long time. Filtering on that will definitely reduce the data transfer.

**Comment by themalkolm** [comment]
Yeah, so this makes UI fast while still requires backend to fetch all data. This is somehow OK as we are OK to give even a dedicated host just for backend to run nicely :) Trading resources for speed of development here.
